version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: pip
  directory: "/src"
  schedule:
    interval: daily
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
