language: python
dist: xenial

services:
  - docker

before_install:
  - git fetch origin +refs/heads/$TRAVIS_BRANCH
  - docker pull gcr.io/clusterfuzz-images/ci

script: ./local/tests/travis_build.bash
