# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
- id: Initialize git
  name: gcr.io/cloud-builders/git
  entrypoint: /bin/bash
  args:
  - -exc
  - |
    # Cloud Build x GitHub integration uses source archives to fetch
    # the source, rather than Git source fetching, and as a consequence
    # does not include the .git/ directory. As a workaround, we clone
    # the repository to grab the .git directory.
    git clone 'https://github.com/google/clusterfuzz' tmp
    git -C tmp fetch origin "$COMMIT_SHA"
    git -C tmp checkout -qf FETCH_HEAD
    mv tmp/.git .git
    rm -rf tmp
- id: Lint
  name: 'gcr.io/clusterfuzz-images/ci'
  args: ['python', 'butler.py', 'lint']
  env:
    - 'GOOGLE_CLOUDBUILD=1'
- name: 'gcr.io/clusterfuzz-images/ci'
  args: ['setup']
- name: 'gcr.io/clusterfuzz-images/ci'
  args:
    - 'bash'
    - '-ex'
    - 'local/tests/run_all_tests'
timeout: 3600s
options:
  machineType: N1_HIGHCPU_32
