# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the 'License');
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an 'AS IS' BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Fuzzer stats schema."""

_COMMON_COLUMNS = [{
    'mode': 'NULLABLE',
    'name': 'kind',
    'type': 'STRING'
}, {
    'mode': 'NULLABLE',
    'name': 'timestamp',
    'type': 'FLOAT'
}, {
    'mode': 'REPEATED',
    'name': 'command',
    'type': 'STRING'
}, {
    'mode': 'NULLABLE',
    'name': 'build_revision',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'fuzzer',
    'type': 'STRING'
}, {
    'mode': 'NULLABLE',
    'name': 'job',
    'type': 'string'
}, {
    'mode': 'NULLABLE',
    'name': 'source',
    'type': 'STRING'
}]

_AFL_SCHEMA = [{
    'mode': 'NULLABLE',
    'name': 'dict_used',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'new_units_generated',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'crash_count',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'manual_dict_size',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'timeout_count',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'stability',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'corpus_crash_count',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'startup_crash_count',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'timeout_limit',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'strategy_corpus_subset',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'bad_instrumentation',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'average_exec_per_sec',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'corpus_size',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'new_units_added',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'log_lines_unwanted',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'actual_duration',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'expected_duration',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'oom_count',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'log_lines_ignored',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'strategy_corpus_mutations',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'read_units',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'max_len',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'log_lines_from_engine',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'slow_unit_count',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'strategy_value_profile',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'leak_count',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'strategy_corpus_mutations_radamsa',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'strategy_selection_method',
    'type': 'STRING'
}] + _COMMON_COLUMNS

_LIBFUZZER_SCHEMA = [{
    'mode': 'NULLABLE',
    'name': 'max_len',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'log_lines_ignored',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'feature_coverage',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'average_exec_per_sec',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'crash_count',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'expected_duration',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'leak_count',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'strategy_corpus_subset',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'number_of_executed_units',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'slow_unit_count',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'strategy_corpus_mutations_radamsa',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'log_lines_from_engine',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'merge_edge_coverage',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'strategy_random_max_len',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'peak_rss_mb',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'corpus_crash_count',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'startup_crash_count',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'edge_coverage',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'new_units_generated',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'initial_feature_coverage',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'manual_dict_size',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'strategy_fork',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'bad_instrumentation',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'initial_edge_coverage',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'timeout_limit',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'dict_used',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'fuzzing_time_percent',
    'type': 'FLOAT'
}, {
    'name': 'new_features',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'log_lines_unwanted',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'slowest_unit_time_sec',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'edges_total',
    'type': 'INTEGER'
}, {
    'name': 'new_edges',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'timeout_count',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'strategy_entropic',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'slow_units_count',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'oom_count',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'strategy_selection_method',
    'type': 'STRING'
}, {
    'mode': 'NULLABLE',
    'name': 'actual_duration',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'strategy_value_profile',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'corpus_size',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'new_units_added',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'corpus_rss_mb',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'merge_new_files',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'merge_new_features',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'strategy_handle_unstable',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'strategy_weighted_mutations',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'strategy_corpus_mutations',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'read_units',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'seed_corpus_rss',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'edge_coverage_count',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'strategy_extra_sanitizers',
    'type': 'INTEGER'
}] + _COMMON_COLUMNS

_HONGGFUZZ_SCHEMA = [{
    'mode': 'NULLABLE',
    'name': 'timeout_count',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'branch_coverage_percent',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'guard_nb',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'crashes_count',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'new_units_added',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'slowest_unit_ms',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'peak_rss_mb',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'iterations',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'time',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'speed',
    'type': 'INTEGER'
}] + _COMMON_COLUMNS

_CENTIPEDE_SCHEMA = [{
    'mode': 'NULLABLE',
    'name': 'NumCoveredPcs_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumCoveredPcs_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumCoveredPcs_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'NumExecs_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumExecs_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumExecs_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'ActiveCorpusSize_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'ActiveCorpusSize_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'ActiveCorpusSize_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'MaxEltSize_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'MaxEltSize_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'MaxEltSize_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'AvgEltSize_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'AvgEltSize_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'AvgEltSize_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'UnixMicros_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'UnixMicros_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'FuzzTimeSec_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'FuzzTimeSec_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'FuzzTimeSec_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'NumProxyCrashes_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumProxyCrashes_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumProxyCrashes_Sum',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'TotalCorpusSize_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'TotalCorpusSize_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'TotalCorpusSize_Sum',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'Num8BitCounterFts_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'Num8BitCounterFts_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'Num8BitCounterFts_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'NumDataFlowFts_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumDataFlowFts_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumDataFlowFts_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'NumCmpFts_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumCmpFts_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumCmpFts_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'NumCallStackFts_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumCallStackFts_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumCallStackFts_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'NumBoundedPathFts_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumBoundedPathFts_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumBoundedPathFts_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'NumPcPairFts_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumPcPairFts_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumPcPairFts_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUserFts_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUserFts_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUserFts_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUnknownFts_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUnknownFts_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUnknownFts_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'NumFuncsInFrontier_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumFuncsInFrontier_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumFuncsInFrontier_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'EngineRusageAvgCores_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'EngineRusageCpuPct_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'EngineRusageRssMb_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'EngineRusageVSizeMb_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser0Fts_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser0Fts_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser0Fts_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser1Fts_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser1Fts_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser1Fts_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser2Fts_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser2Fts_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser2Fts_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser3Fts_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser3Fts_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser3Fts_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser4Fts_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser4Fts_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser4Fts_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser5Fts_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser5Fts_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser5Fts_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser6Fts_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser6Fts_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser6Fts_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser7Fts_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser7Fts_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser7Fts_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser8Fts_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser8Fts_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser8Fts_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser9Fts_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser9Fts_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser9Fts_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser10Fts_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser10Fts_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser10Fts_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser11Fts_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser11Fts_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser11Fts_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser12Fts_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser12Fts_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser12Fts_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser13Fts_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser13Fts_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser13Fts_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser14Fts_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser14Fts_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser14Fts_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser15Fts_Min',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser15Fts_Max',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'NumUser15Fts_Avg',
    'type': 'FLOAT'
}, {
    'mode': 'NULLABLE',
    'name': 'crash_count',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'oom_count',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'timeout_count',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'leak_count',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'expected_duration',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'actual_duration',
    'type': 'INTEGER'
}, {
    'mode': 'NULLABLE',
    'name': 'fuzzing_time_percent',
    'type': 'FLOAT'
}] + _COMMON_COLUMNS

_SCHEMA = {
    'afl': _AFL_SCHEMA,
    'honggfuzz': _HONGGFUZZ_SCHEMA,
    'libFuzzer': _LIBFUZZER_SCHEMA,
    'centipede': _CENTIPEDE_SCHEMA,
}


def get(engine_name):
  """Get the schema for an engine name."""
  schema = _SCHEMA.get(engine_name)
  if not schema:
    return None

  return {'fields': schema}
