"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2026 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

This file is based on https://source.chromium.org/chromium/infra/infra_superproject/+/main:infra/luci/appengine/swarming/proto/api_v2/swarming.proto
This includes necessary messages to construct a NewTaskRequest
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _StateQuery:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _StateQueryEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_StateQuery.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    QUERY_PENDING: _StateQuery.ValueType  # 0
    """Query for all tasks currently TaskState.PENDING."""
    QUERY_RUNNING: _StateQuery.ValueType  # 1
    """Query for all tasks currently TaskState.RUNNING. This includes tasks
    currently in the overhead phase; mapping input files or archiving outputs
    back to the server.
    """
    QUERY_PENDING_RUNNING: _StateQuery.ValueType  # 2
    """Query for all tasks currently TaskState.PENDING or TaskState.RUNNING. This
    is the query for the 'active' tasks.
    """
    QUERY_COMPLETED: _StateQuery.ValueType  # 3
    """Query for all tasks that completed normally as TaskState.COMPLETED,
    independent of the process exit code.
    """
    QUERY_COMPLETED_SUCCESS: _StateQuery.ValueType  # 4
    """Query for all tasks that completed normally as TaskState.COMPLETED and that
    had exit code 0.
    """
    QUERY_COMPLETED_FAILURE: _StateQuery.ValueType  # 5
    """Query for all tasks that completed normally as TaskState.COMPLETED and that
    had exit code not 0.
    """
    QUERY_EXPIRED: _StateQuery.ValueType  # 6
    """Query for all tasks that are TaskState.EXPIRED."""
    QUERY_TIMED_OUT: _StateQuery.ValueType  # 7
    """Query for all tasks that are TaskState.TIMED_OUT."""
    QUERY_BOT_DIED: _StateQuery.ValueType  # 8
    """Query for all tasks that are TaskState.BOT_DIED."""
    QUERY_CANCELED: _StateQuery.ValueType  # 9
    """Query for all tasks that are TaskState.CANCELED."""
    QUERY_ALL: _StateQuery.ValueType  # 10
    """Query for all tasks, independent of the task state.

    In hindsight, this constant should have been the value 0. Sorry, the
    original author was young and foolish.
    """
    QUERY_DEDUPED: _StateQuery.ValueType  # 11
    """Query for all tasks that are TaskState.COMPLETED but that actually didn't
    run due to TaskProperties.idempotent being True *and* that a previous task
    with the exact same TaskProperties had successfully run before, aka
    COMPLETED_SUCCESS.
    """
    QUERY_KILLED: _StateQuery.ValueType  # 12
    """Query for all tasks that are TaskState.KILLED."""
    QUERY_NO_RESOURCE: _StateQuery.ValueType  # 13
    """Query for all tasks that are TaskState.NO_RESOURCE."""
    QUERY_CLIENT_ERROR: _StateQuery.ValueType  # 14
    """Query for all tasks that are TaskState.CLIENT_ERROR."""

class StateQuery(_StateQuery, metaclass=_StateQueryEnumTypeWrapper):
    """Enums

    Use one of the values in this enum to query for tasks in one of the
    specified state.

    Use 'ALL' to not use any filtering based on task state.

    As an example, this enum enables querying for all tasks with state COMPLETED
    but non-zero exit code via COMPLETED_FAILURE.

    Do not confuse StateQuery and TaskState. StateQuery is to query tasks
    via the API. TaskState is the current task state.
    """

QUERY_PENDING: StateQuery.ValueType  # 0
"""Query for all tasks currently TaskState.PENDING."""
QUERY_RUNNING: StateQuery.ValueType  # 1
"""Query for all tasks currently TaskState.RUNNING. This includes tasks
currently in the overhead phase; mapping input files or archiving outputs
back to the server.
"""
QUERY_PENDING_RUNNING: StateQuery.ValueType  # 2
"""Query for all tasks currently TaskState.PENDING or TaskState.RUNNING. This
is the query for the 'active' tasks.
"""
QUERY_COMPLETED: StateQuery.ValueType  # 3
"""Query for all tasks that completed normally as TaskState.COMPLETED,
independent of the process exit code.
"""
QUERY_COMPLETED_SUCCESS: StateQuery.ValueType  # 4
"""Query for all tasks that completed normally as TaskState.COMPLETED and that
had exit code 0.
"""
QUERY_COMPLETED_FAILURE: StateQuery.ValueType  # 5
"""Query for all tasks that completed normally as TaskState.COMPLETED and that
had exit code not 0.
"""
QUERY_EXPIRED: StateQuery.ValueType  # 6
"""Query for all tasks that are TaskState.EXPIRED."""
QUERY_TIMED_OUT: StateQuery.ValueType  # 7
"""Query for all tasks that are TaskState.TIMED_OUT."""
QUERY_BOT_DIED: StateQuery.ValueType  # 8
"""Query for all tasks that are TaskState.BOT_DIED."""
QUERY_CANCELED: StateQuery.ValueType  # 9
"""Query for all tasks that are TaskState.CANCELED."""
QUERY_ALL: StateQuery.ValueType  # 10
"""Query for all tasks, independent of the task state.

In hindsight, this constant should have been the value 0. Sorry, the
original author was young and foolish.
"""
QUERY_DEDUPED: StateQuery.ValueType  # 11
"""Query for all tasks that are TaskState.COMPLETED but that actually didn't
run due to TaskProperties.idempotent being True *and* that a previous task
with the exact same TaskProperties had successfully run before, aka
COMPLETED_SUCCESS.
"""
QUERY_KILLED: StateQuery.ValueType  # 12
"""Query for all tasks that are TaskState.KILLED."""
QUERY_NO_RESOURCE: StateQuery.ValueType  # 13
"""Query for all tasks that are TaskState.NO_RESOURCE."""
QUERY_CLIENT_ERROR: StateQuery.ValueType  # 14
"""Query for all tasks that are TaskState.CLIENT_ERROR."""
global___StateQuery = StateQuery

class _TaskState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TaskStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TaskState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    INVALID: _TaskState.ValueType  # 0
    """Invalid state, do not use."""
    RUNNING: _TaskState.ValueType  # 16
    """The task is currently running. This is in fact 3 phases: the initial
    overhead to fetch input files, the actual task running, and the tear down
    overhead to archive output files to the server.
    """
    PENDING: _TaskState.ValueType  # 32
    """The task is currently pending. This means that no bot reaped the task. It
    will stay in this state until either a task reaps it or the expiration
    elapsed. The task pending expiration is specified as
    TaskSlice.expiration_secs, one per task slice.
    """
    EXPIRED: _TaskState.ValueType  # 48
    """The task is not pending anymore, and never ran due to lack of capacity. This
    means that other higher priority tasks ran instead and that not enough bots
    were available to run this task for TaskSlice.expiration_secs seconds.
    """
    TIMED_OUT: _TaskState.ValueType  # 64
    """The task ran for longer than the allowed time in
    TaskProperties.execution_timeout_secs or TaskProperties.io_timeout_secs.
    This means the bot forcefully killed the task process as described in the
    graceful termination dance in the documentation.
    """
    BOT_DIED: _TaskState.ValueType  # 80
    """The task ran but the bot had an internal failure, unrelated to the task
    itself. It can be due to the server being unavailable to get task update,
    the host on which the bot is running crashing or rebooting, etc.
    """
    CANCELED: _TaskState.ValueType  # 96
    """The task never ran, and was manually cancelled via the 'cancel' API before
    it was reaped.
    """
    COMPLETED: _TaskState.ValueType  # 112
    """The task ran and completed normally. The task process exit code may be 0 or
    another value.
    """
    KILLED: _TaskState.ValueType  # 128
    """The task ran but was manually killed via the 'cancel' API. This means the
    bot forcefully killed the task process as described in the graceful
    termination dance in the documentation.
    """
    NO_RESOURCE: _TaskState.ValueType  # 256
    """The task was never set to PENDING and was immediately refused, as the server
    determined that there is no bot capacity to run this task. This happens
    because no bot exposes a superset of the requested task dimensions.

    Set TaskSlice.wait_for_capacity to True to force the server to keep the task
    slice pending even in this case. Generally speaking, the task will
    eventually switch to EXPIRED, as there's no bot to run it. That said, there
    are situations where it is known that in some not-too-distant future a wild
    bot will appear that will be able to run this task.
    """
    CLIENT_ERROR: _TaskState.ValueType  # 512
    """The task run into an issue that was caused by the client. It can be due to
    a bad CIPD or CAS package. Retrying the task with the same parameters will
    not change the result.
    """

class TaskState(_TaskState, metaclass=_TaskStateEnumTypeWrapper):
    """Represents the current task state.

    Some states are still mutable: PENDING and RUNNING. The others are final and
    will not change afterward.

    A task is guaranteed to be in exactly one state at any point of time.

    Do not confuse StateQuery and TaskState. StateQuery is to query tasks
    via the API. TaskState is the current task state.

    As you read the following constants, astute readers may wonder why these
    constants look like a bitmask. This is because of historical reasons and this
    is effectively an enum, not a bitmask.
    """

INVALID: TaskState.ValueType  # 0
"""Invalid state, do not use."""
RUNNING: TaskState.ValueType  # 16
"""The task is currently running. This is in fact 3 phases: the initial
overhead to fetch input files, the actual task running, and the tear down
overhead to archive output files to the server.
"""
PENDING: TaskState.ValueType  # 32
"""The task is currently pending. This means that no bot reaped the task. It
will stay in this state until either a task reaps it or the expiration
elapsed. The task pending expiration is specified as
TaskSlice.expiration_secs, one per task slice.
"""
EXPIRED: TaskState.ValueType  # 48
"""The task is not pending anymore, and never ran due to lack of capacity. This
means that other higher priority tasks ran instead and that not enough bots
were available to run this task for TaskSlice.expiration_secs seconds.
"""
TIMED_OUT: TaskState.ValueType  # 64
"""The task ran for longer than the allowed time in
TaskProperties.execution_timeout_secs or TaskProperties.io_timeout_secs.
This means the bot forcefully killed the task process as described in the
graceful termination dance in the documentation.
"""
BOT_DIED: TaskState.ValueType  # 80
"""The task ran but the bot had an internal failure, unrelated to the task
itself. It can be due to the server being unavailable to get task update,
the host on which the bot is running crashing or rebooting, etc.
"""
CANCELED: TaskState.ValueType  # 96
"""The task never ran, and was manually cancelled via the 'cancel' API before
it was reaped.
"""
COMPLETED: TaskState.ValueType  # 112
"""The task ran and completed normally. The task process exit code may be 0 or
another value.
"""
KILLED: TaskState.ValueType  # 128
"""The task ran but was manually killed via the 'cancel' API. This means the
bot forcefully killed the task process as described in the graceful
termination dance in the documentation.
"""
NO_RESOURCE: TaskState.ValueType  # 256
"""The task was never set to PENDING and was immediately refused, as the server
determined that there is no bot capacity to run this task. This happens
because no bot exposes a superset of the requested task dimensions.

Set TaskSlice.wait_for_capacity to True to force the server to keep the task
slice pending even in this case. Generally speaking, the task will
eventually switch to EXPIRED, as there's no bot to run it. That said, there
are situations where it is known that in some not-too-distant future a wild
bot will appear that will be able to run this task.
"""
CLIENT_ERROR: TaskState.ValueType  # 512
"""The task run into an issue that was caused by the client. It can be due to
a bad CIPD or CAS package. Retrying the task with the same parameters will
not change the result.
"""
global___TaskState = TaskState

@typing_extensions.final
class StringPair(google.protobuf.message.Message):
    """Messages

    Represents a mapping of string to a string.

    If the StringPair is itself repeated inside another message, the list
    must be sorted by key and the keys must be unique.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    key: builtins.str
    value: builtins.str
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        value: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

global___StringPair = StringPair

@typing_extensions.final
class StringListPair(google.protobuf.message.Message):
    """Represents a mapping of string to a list of strings.

    If the StringListPair is itself repeated inside another message, the list
    must be sorted by key and the keys must be unique.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    key: builtins.str
    @property
    def value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """All the values for this key. values must be sorted. Human readable.

        This string should make sense to a user in the context of 'key'.
        """
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        value: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

global___StringListPair = StringListPair

@typing_extensions.final
class Digest(google.protobuf.message.Message):
    """This is a [Digest][build.bazel.remote.execution.v2.Digest] of a blob on
    RBE-CAS. See the explanations at the original definition.
    pylint: disable=line-too-long
    https://github.com/bazelbuild/remote-apis/blob/77cfb44a88577a7ade5dd2400425f6d50469ec6d/build/bazel/remote/execution/v2/remote_execution.proto#L753-L791
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HASH_FIELD_NUMBER: builtins.int
    SIZE_BYTES_FIELD_NUMBER: builtins.int
    hash: builtins.str
    size_bytes: builtins.int
    def __init__(
        self,
        *,
        hash: builtins.str = ...,
        size_bytes: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["hash", b"hash", "size_bytes", b"size_bytes"]) -> None: ...

global___Digest = Digest

@typing_extensions.final
class CASReference(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CAS_INSTANCE_FIELD_NUMBER: builtins.int
    DIGEST_FIELD_NUMBER: builtins.int
    cas_instance: builtins.str
    """Full name of RBE-CAS instance. `projects/{project_id}/instances/{instance}`.
    e.g. projects/chromium-swarm/instances/default_instance
    """
    @property
    def digest(self) -> global___Digest:
        """CAS Digest consists of hash and size bytes."""
    def __init__(
        self,
        *,
        cas_instance: builtins.str = ...,
        digest: global___Digest | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["digest", b"digest"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["cas_instance", b"cas_instance", "digest", b"digest"]) -> None: ...

global___CASReference = CASReference

@typing_extensions.final
class CipdPackage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PACKAGE_NAME_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    package_name: builtins.str
    """A CIPD package to install in the run dir before task execution.\"\"\"
    A template of a full CIPD package name, e.g.
    "infra/tools/authutil/${platform}"
    See also cipd.ALL_PARAMS.
    """
    version: builtins.str
    """Valid package version for all packages matched by package name."""
    path: builtins.str
    """Path to dir, relative to the root dir, where to install the package.
    If empty, the package will be installed a the root of the mapped directory.
    If file names in the package and in the isolate clash, it will cause a
    failure.
    """
    def __init__(
        self,
        *,
        package_name: builtins.str = ...,
        version: builtins.str = ...,
        path: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["package_name", b"package_name", "path", b"path", "version", b"version"]) -> None: ...

global___CipdPackage = CipdPackage

@typing_extensions.final
class CipdInput(google.protobuf.message.Message):
    """Defines CIPD packages to install in task run directory."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVER_FIELD_NUMBER: builtins.int
    CLIENT_PACKAGE_FIELD_NUMBER: builtins.int
    PACKAGES_FIELD_NUMBER: builtins.int
    server: builtins.str
    """URL of the CIPD server. Must start with "https://" or "http://".
    This field or its subfields are optional if default cipd client is defined
    in the server config.
    """
    @property
    def client_package(self) -> global___CipdPackage:
        """CIPD package of CIPD client to use.
        client_package.version is required.
        This field is optional is default value is defined in the server config.
        client_package.path must be empty.
        """
    @property
    def packages(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CipdPackage]:
        """List of CIPD packages to install."""
    def __init__(
        self,
        *,
        server: builtins.str = ...,
        client_package: global___CipdPackage | None = ...,
        packages: collections.abc.Iterable[global___CipdPackage] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["client_package", b"client_package"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["client_package", b"client_package", "packages", b"packages", "server", b"server"]) -> None: ...

global___CipdInput = CipdInput

@typing_extensions.final
class CipdPins(google.protobuf.message.Message):
    """Defines pinned CIPD packages that were installed during the task."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLIENT_PACKAGE_FIELD_NUMBER: builtins.int
    PACKAGES_FIELD_NUMBER: builtins.int
    @property
    def client_package(self) -> global___CipdPackage:
        """The pinned package + version of the CIPD client that was actually used."""
    @property
    def packages(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CipdPackage]:
        """List of CIPD packages that were installed in the task with fully resolved
        package names and versions.
        """
    def __init__(
        self,
        *,
        client_package: global___CipdPackage | None = ...,
        packages: collections.abc.Iterable[global___CipdPackage] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["client_package", b"client_package"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["client_package", b"client_package", "packages", b"packages"]) -> None: ...

global___CipdPins = CipdPins

@typing_extensions.final
class CacheEntry(google.protobuf.message.Message):
    """Describes a named cache that should be present on the bot.

    A CacheEntry in a task specified that the task prefers the cache to be present
    on the bot. A symlink to the cache directory is created at <run_dir>/|path|.
    If cache is not present on the machine, the directory is empty.
    If the tasks makes any changes to the contents of the cache directory, they
    are persisted on the machine. If another task runs on the same machine and
    requests the same named cache, even if mapped to a different path, it will see
    the changes.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Unique name of the cache. Required. Length is limited to 4096."""
    path: builtins.str
    """Relative path to the directory that will be linked to the named cache.
    Required.
    A path cannot be shared among multiple caches or CIPD installations.
    A task will fail if a file/dir with the same name already exists.
    """
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        path: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name", "path", b"path"]) -> None: ...

global___CacheEntry = CacheEntry

@typing_extensions.final
class Containment(google.protobuf.message.Message):
    """Defines the type of "sandbox" to run the task process in.

    Unimplemented.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _ContainmentType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ContainmentTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Containment._ContainmentType.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        NOT_SPECIFIED: Containment._ContainmentType.ValueType  # 0
        """Historical value, not specified. Containment may or may not be used."""
        NONE: Containment._ContainmentType.ValueType  # 1
        """No containment, the default for now."""
        AUTO: Containment._ContainmentType.ValueType  # 2
        """Use the containment appropriate on the platform."""
        JOB_OBJECT: Containment._ContainmentType.ValueType  # 3
        """Use Job Object on Windows. Will fail if used on other platforms."""

    class ContainmentType(_ContainmentType, metaclass=_ContainmentTypeEnumTypeWrapper): ...
    NOT_SPECIFIED: Containment.ContainmentType.ValueType  # 0
    """Historical value, not specified. Containment may or may not be used."""
    NONE: Containment.ContainmentType.ValueType  # 1
    """No containment, the default for now."""
    AUTO: Containment.ContainmentType.ValueType  # 2
    """Use the containment appropriate on the platform."""
    JOB_OBJECT: Containment.ContainmentType.ValueType  # 3
    """Use Job Object on Windows. Will fail if used on other platforms."""

    LOWER_PRIORITY_FIELD_NUMBER: builtins.int
    CONTAINMENT_TYPE_FIELD_NUMBER: builtins.int
    LIMIT_PROCESSES_FIELD_NUMBER: builtins.int
    LIMIT_TOTAL_COMMITTED_MEMORY_FIELD_NUMBER: builtins.int
    lower_priority: builtins.bool
    """Lowers the priority of the task process when started. Doesn't require
    containment. This gives the bot a chance to survive when the task starts an
    overwhelming number of children processes.
    """
    containment_type: global___Containment.ContainmentType.ValueType
    """Defines the type of containment used."""
    limit_processes: builtins.int
    """The values below require a form of containment to be enforced.

    Limits the number of concurrent active processes.
    """
    limit_total_committed_memory: builtins.int
    """Limits the total amount of memory allocated by processes."""
    def __init__(
        self,
        *,
        lower_priority: builtins.bool = ...,
        containment_type: global___Containment.ContainmentType.ValueType = ...,
        limit_processes: builtins.int = ...,
        limit_total_committed_memory: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["containment_type", b"containment_type", "limit_processes", b"limit_processes", "limit_total_committed_memory", b"limit_total_committed_memory", "lower_priority", b"lower_priority"]) -> None: ...

global___Containment = Containment

@typing_extensions.final
class TaskProperties(google.protobuf.message.Message):
    """Important metadata about a particular task."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CACHES_FIELD_NUMBER: builtins.int
    CIPD_INPUT_FIELD_NUMBER: builtins.int
    COMMAND_FIELD_NUMBER: builtins.int
    RELATIVE_CWD_FIELD_NUMBER: builtins.int
    DIMENSIONS_FIELD_NUMBER: builtins.int
    ENV_FIELD_NUMBER: builtins.int
    ENV_PREFIXES_FIELD_NUMBER: builtins.int
    EXECUTION_TIMEOUT_SECS_FIELD_NUMBER: builtins.int
    GRACE_PERIOD_SECS_FIELD_NUMBER: builtins.int
    IDEMPOTENT_FIELD_NUMBER: builtins.int
    CAS_INPUT_ROOT_FIELD_NUMBER: builtins.int
    IO_TIMEOUT_SECS_FIELD_NUMBER: builtins.int
    OUTPUTS_FIELD_NUMBER: builtins.int
    SECRET_BYTES_FIELD_NUMBER: builtins.int
    CONTAINMENT_FIELD_NUMBER: builtins.int
    @property
    def caches(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CacheEntry]:
        """Specifies named caches to map into the working directory. These caches
        outlives the task, which can then be reused by tasks later used on this bot
        that request the same named cache.
        """
    @property
    def cipd_input(self) -> global___CipdInput:
        """CIPD packages to install. These packages are meant to be software that is
        needed (a dependency) to the task being run. Unlike isolated files, the CIPD
        packages do not expire from the server.
        """
    @property
    def command(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Command to run. This has priority over a command specified in the isolated
        files.
        """
    relative_cwd: builtins.str
    """Relative working directory to start the 'command' in, defaults to the root
    mapped directory or what is provided in the isolated file, if any.
    """
    @property
    def dimensions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StringPair]:
        """Dimensions are what is used to determine which bot can run the task. The
        bot must have all the matching dimensions, even for repeated keys with
        multiple different values. It is a logical AND, all values must match.

        It should have been a StringListPair but this would be a breaking change.
        """
    @property
    def env(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StringPair]:
        """Environment variables to set when running the task."""
    @property
    def env_prefixes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StringListPair]:
        """Swarming-root relative paths to prepend to a given environment variable.

        These allow you to put certain subdirectories of the task into PATH,
        PYTHONPATH, or other PATH-like environment variables. The order of
        operations is:
          * Turn slashes into native-platform slashes.
          * Make the path absolute
          * Prepend it to the current value of the envvar using the os-native list
            separator (i.e. `;` on windows, `:` on POSIX).

        Each envvar can have multiple paths to prepend. They will be prepended in
        the order seen here.

        For example, if env_prefixes was:
          [("PATH", ["foo", "bar"]),
           ("CUSTOMPATH", ["custom"])]

        The task would see:
          PATH=/path/to/swarming/rundir/foo:/path/to/swarming/rundir/bar:$PATH
          CUSTOMPATH=/path/to/swarming/rundir/custom

        The path should always be specified here with forward-slashes, and it must
        not attempt to escape the swarming root (i.e. must not contain `..`).

        These are applied AFTER evaluating `env` entries.
        """
    execution_timeout_secs: builtins.int
    """Maximum number of seconds the task can run before its process is forcibly
    terminated and the task results in TIMED_OUT.
    """
    grace_period_secs: builtins.int
    """Number of second to give the child process after a SIGTERM before sending a
    SIGKILL. See doc/Bot.md#timeout-handling
    """
    idempotent: builtins.bool
    """True if the task does not access any service through the network and is
    believed to be 100% reproducible with the same outcome. In the case of a
    successful task, previous results will be reused if possible.
    """
    @property
    def cas_input_root(self) -> global___CASReference:
        """Digest of the input root uploaded to RBE-CAS.
        This MUST be digest of [build.bazel.remote.execution.v2.Directory].
        """
    io_timeout_secs: builtins.int
    """Maximum number of seconds the task may be silent (no output to stdout nor
    stderr) before it is considered hung and it forcibly terminated early and
    the task results in TIMED_OUT.
    """
    @property
    def outputs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Paths in the working directory to archive back."""
    secret_bytes: builtins.bytes
    """Secret bytes to provide to the task. Cannot be retrieved back."""
    @property
    def containment(self) -> global___Containment:
        """Containment of the task processes."""
    def __init__(
        self,
        *,
        caches: collections.abc.Iterable[global___CacheEntry] | None = ...,
        cipd_input: global___CipdInput | None = ...,
        command: collections.abc.Iterable[builtins.str] | None = ...,
        relative_cwd: builtins.str = ...,
        dimensions: collections.abc.Iterable[global___StringPair] | None = ...,
        env: collections.abc.Iterable[global___StringPair] | None = ...,
        env_prefixes: collections.abc.Iterable[global___StringListPair] | None = ...,
        execution_timeout_secs: builtins.int = ...,
        grace_period_secs: builtins.int = ...,
        idempotent: builtins.bool = ...,
        cas_input_root: global___CASReference | None = ...,
        io_timeout_secs: builtins.int = ...,
        outputs: collections.abc.Iterable[builtins.str] | None = ...,
        secret_bytes: builtins.bytes = ...,
        containment: global___Containment | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["cas_input_root", b"cas_input_root", "cipd_input", b"cipd_input", "containment", b"containment"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["caches", b"caches", "cas_input_root", b"cas_input_root", "cipd_input", b"cipd_input", "command", b"command", "containment", b"containment", "dimensions", b"dimensions", "env", b"env", "env_prefixes", b"env_prefixes", "execution_timeout_secs", b"execution_timeout_secs", "grace_period_secs", b"grace_period_secs", "idempotent", b"idempotent", "io_timeout_secs", b"io_timeout_secs", "outputs", b"outputs", "relative_cwd", b"relative_cwd", "secret_bytes", b"secret_bytes"]) -> None: ...

global___TaskProperties = TaskProperties

@typing_extensions.final
class TaskSlice(google.protobuf.message.Message):
    """Defines a possible task execution for a task request to be run on the
    Swarming infrastructure.

    This is one of the possible fallback on a task request.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROPERTIES_FIELD_NUMBER: builtins.int
    EXPIRATION_SECS_FIELD_NUMBER: builtins.int
    WAIT_FOR_CAPACITY_FIELD_NUMBER: builtins.int
    @property
    def properties(self) -> global___TaskProperties:
        """The property of the task to try to run.

        If there is no bot that can serve this properties.dimensions when this task
        slice is enqueued, it is immediately denied. This can trigger if:
        - There is no bot with these dimensions currently known.
        - Bots that could run this task are either all dead or quarantined.
        Swarming considers a bot dead if it hasn't pinged in the last N minutes
        (currently 10 minutes).
        """
    expiration_secs: builtins.int
    """Maximum of seconds the task slice may stay PENDING.

    If this task request slice is not scheduled after waiting this long, the
    next one will be processed. If this slice is the last one, the task state
    will be set to EXPIRED.
    """
    wait_for_capacity: builtins.bool
    """When a task is scheduled and there are currently no bots available to run
    the task, the TaskSlice can either be PENDING, or be denied immediately.
    When denied, the next TaskSlice is enqueued, and if there's no following
    TaskSlice, the task state is set to NO_RESOURCE. This should normally be
    set to False to avoid unnecessary waiting.
    """
    def __init__(
        self,
        *,
        properties: global___TaskProperties | None = ...,
        expiration_secs: builtins.int = ...,
        wait_for_capacity: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["properties", b"properties"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["expiration_secs", b"expiration_secs", "properties", b"properties", "wait_for_capacity", b"wait_for_capacity"]) -> None: ...

global___TaskSlice = TaskSlice

@typing_extensions.final
class ResultDBInfo(google.protobuf.message.Message):
    """ResultDB properties of a completed task."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HOSTNAME_FIELD_NUMBER: builtins.int
    INVOCATION_FIELD_NUMBER: builtins.int
    hostname: builtins.str
    """ResultDB hostname, e.g. "results.api.cr.dev" """
    invocation: builtins.str
    """Name of the task's ResultDB invocation.

    For example "invocations/task-chromium-swarm.appspot.com-deadbeef1".
    Unset if Swarming:ResultDB integration was not enabled for this task.

    If the task was deduplicated, this equals invocation name of the original
    task.
    """
    def __init__(
        self,
        *,
        hostname: builtins.str = ...,
        invocation: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["hostname", b"hostname", "invocation", b"invocation"]) -> None: ...

global___ResultDBInfo = ResultDBInfo

@typing_extensions.final
class ResultDBCfg(google.protobuf.message.Message):
    """Swarming:ResultDB integration configuration for a task.
    See NewTaskRequest.resultdb for more details.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENABLE_FIELD_NUMBER: builtins.int
    enable: builtins.bool
    """If True and this task is not deduplicated, create
    "task-{swarming_hostname}-{run_id}" invocation for this task,
    provide its update token to the task subprocess via LUCI_CONTEXT
    and finalize the invocation when the task is done.
    If the task is deduplicated, then TaskResult.invocation_name will be the
    invocation name of the original task.
    Swarming:ResultDB integration is off by default, but it may change in the
    future.
    """
    def __init__(
        self,
        *,
        enable: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["enable", b"enable"]) -> None: ...

global___ResultDBCfg = ResultDBCfg

@typing_extensions.final
class NewTaskRequest(google.protobuf.message.Message):
    """Description of a new task request as described by the client.
    This message is used to create a new task.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _PoolTaskTemplateField:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _PoolTaskTemplateFieldEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[NewTaskRequest._PoolTaskTemplateField.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        AUTO: NewTaskRequest._PoolTaskTemplateField.ValueType  # 0
        CANARY_PREFER: NewTaskRequest._PoolTaskTemplateField.ValueType  # 1
        CANARY_NEVER: NewTaskRequest._PoolTaskTemplateField.ValueType  # 2
        SKIP: NewTaskRequest._PoolTaskTemplateField.ValueType  # 3

    class PoolTaskTemplateField(_PoolTaskTemplateField, metaclass=_PoolTaskTemplateFieldEnumTypeWrapper):
        """Controls the application of the pool's TaskTemplate to the creation of this
        task. By default this will automatically select the pool's preference for
        template, but you can also instruct swarming to prefer/prevent the
        application of canary templates, as well as skipping the template
        altogether.
        """

    AUTO: NewTaskRequest.PoolTaskTemplateField.ValueType  # 0
    CANARY_PREFER: NewTaskRequest.PoolTaskTemplateField.ValueType  # 1
    CANARY_NEVER: NewTaskRequest.PoolTaskTemplateField.ValueType  # 2
    SKIP: NewTaskRequest.PoolTaskTemplateField.ValueType  # 3

    EXPIRATION_SECS_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    PARENT_TASK_ID_FIELD_NUMBER: builtins.int
    PRIORITY_FIELD_NUMBER: builtins.int
    PROPERTIES_FIELD_NUMBER: builtins.int
    TASK_SLICES_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    USER_FIELD_NUMBER: builtins.int
    SERVICE_ACCOUNT_FIELD_NUMBER: builtins.int
    PUBSUB_TOPIC_FIELD_NUMBER: builtins.int
    PUBSUB_AUTH_TOKEN_FIELD_NUMBER: builtins.int
    PUBSUB_USERDATA_FIELD_NUMBER: builtins.int
    EVALUATE_ONLY_FIELD_NUMBER: builtins.int
    POOL_TASK_TEMPLATE_FIELD_NUMBER: builtins.int
    BOT_PING_TOLERANCE_SECS_FIELD_NUMBER: builtins.int
    REQUEST_UUID_FIELD_NUMBER: builtins.int
    RESULTDB_FIELD_NUMBER: builtins.int
    REALM_FIELD_NUMBER: builtins.int
    expiration_secs: builtins.int
    """DEPRECATED. Use task_slices[0].expiration_secs."""
    name: builtins.str
    """Task name for display purpose."""
    parent_task_id: builtins.str
    """Parent Swarming run ID of the process requesting this task. This is to tell
    the server about reentrancy: when a task creates children Swarming tasks, so
    that the tree of tasks can be presented in the UI; the parent task will list
    all the children tasks that were triggered.
    """
    priority: builtins.int
    """Task priority, the lower the more important."""
    @property
    def properties(self) -> global___TaskProperties:
        """DEPRECATED. Use task_slices[0].properties."""
    @property
    def task_slices(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TaskSlice]:
        """Slice of TaskSlice, along their scheduling parameters. Cannot be used at the
        same time as properties and expiration_secs.

        This defines all the various possible task execution for a task request to
        be run on the Swarming infrastructure. They are processed in order, and it
        is guaranteed that at most one of these will be processed.
        """
    @property
    def tags(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Tags are 'key:value' strings that describes what the task is about. This can
        later be leveraged to search for kinds of tasks per tag.
        """
    user: builtins.str
    """User on which behalf this task is run, if relevant. Not validated."""
    service_account: builtins.str
    """Defines what OAuth2 credentials the task uses when calling other services.

    Possible values are:
      - 'none': do not use a task service account at all, this is the default.
      - 'bot': use bot's own account, works only if bots authenticate with
          OAuth2.
      - <some email>: use this specific service account if it is allowed in the
          pool (via 'allowed_service_account' pools.cfg setting) and configured
          in the token server's service_accounts.cfg.

    Note that the service account name is specified outside of task properties,
    and thus it is possible to have two tasks with different service accounts,
    but identical properties hash (so one can be deduped). If this is unsuitable
    use 'idempotent=False' or include a service account name in properties
    separately.
    """
    pubsub_topic: builtins.str
    """Full topic name to post task state updates to, e.g.
    "projects/<id>/topics/<id>".
    """
    pubsub_auth_token: builtins.str
    """Secret string to put into "auth_token" attribute of PubSub message."""
    pubsub_userdata: builtins.str
    """Will be but into "userdata" fields of PubSub message."""
    evaluate_only: builtins.bool
    """Only evaluate the task, as if we were going to schedule it, but don't
    actually schedule it. This will return the TaskRequest, but without
    a task_id.
    """
    pool_task_template: global___NewTaskRequest.PoolTaskTemplateField.ValueType
    bot_ping_tolerance_secs: builtins.int
    """Maximum delay between bot pings before the bot is considered dead
    while running a task.
    """
    request_uuid: builtins.str
    """This is used to make new task request idempotent in best effort.
    If new request has request_uuid field, it checks memcache before scheduling
    actual task to check there is already the task triggered by same request
    previously.
    """
    @property
    def resultdb(self) -> global___ResultDBCfg:
        """Configuration of Swarming:ResultDB integration."""
    realm: builtins.str
    """Task realm.
    See api/swarming.proto for more details.
    """
    def __init__(
        self,
        *,
        expiration_secs: builtins.int = ...,
        name: builtins.str = ...,
        parent_task_id: builtins.str = ...,
        priority: builtins.int = ...,
        properties: global___TaskProperties | None = ...,
        task_slices: collections.abc.Iterable[global___TaskSlice] | None = ...,
        tags: collections.abc.Iterable[builtins.str] | None = ...,
        user: builtins.str = ...,
        service_account: builtins.str = ...,
        pubsub_topic: builtins.str = ...,
        pubsub_auth_token: builtins.str = ...,
        pubsub_userdata: builtins.str = ...,
        evaluate_only: builtins.bool = ...,
        pool_task_template: global___NewTaskRequest.PoolTaskTemplateField.ValueType = ...,
        bot_ping_tolerance_secs: builtins.int = ...,
        request_uuid: builtins.str = ...,
        resultdb: global___ResultDBCfg | None = ...,
        realm: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["properties", b"properties", "resultdb", b"resultdb"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bot_ping_tolerance_secs", b"bot_ping_tolerance_secs", "evaluate_only", b"evaluate_only", "expiration_secs", b"expiration_secs", "name", b"name", "parent_task_id", b"parent_task_id", "pool_task_template", b"pool_task_template", "priority", b"priority", "properties", b"properties", "pubsub_auth_token", b"pubsub_auth_token", "pubsub_topic", b"pubsub_topic", "pubsub_userdata", b"pubsub_userdata", "realm", b"realm", "request_uuid", b"request_uuid", "resultdb", b"resultdb", "service_account", b"service_account", "tags", b"tags", "task_slices", b"task_slices", "user", b"user"]) -> None: ...

global___NewTaskRequest = NewTaskRequest

@typing_extensions.final
class TaskRequestMetadataResponse(google.protobuf.message.Message):
    """Provides the ID of the requested TaskRequest."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    TASK_RESULT_FIELD_NUMBER: builtins.int
    task_id: builtins.str
    @property
    def request(self) -> global___TaskRequestResponse: ...
    @property
    def task_result(self) -> global___TaskResultResponse:
        """Set to finished task result in case task was deduplicated."""
    def __init__(
        self,
        *,
        task_id: builtins.str = ...,
        request: global___TaskRequestResponse | None = ...,
        task_result: global___TaskResultResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["request", b"request", "task_result", b"task_result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["request", b"request", "task_id", b"task_id", "task_result", b"task_result"]) -> None: ...

global___TaskRequestMetadataResponse = TaskRequestMetadataResponse

@typing_extensions.final
class TaskRequestResponse(google.protobuf.message.Message):
    """Description of a task request as registered by the server.
    This message is used when retrieving information about an existing task.
    See NewTaskRequest for more details.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: builtins.int
    EXPIRATION_SECS_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    PARENT_TASK_ID_FIELD_NUMBER: builtins.int
    PRIORITY_FIELD_NUMBER: builtins.int
    PROPERTIES_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    CREATED_TS_FIELD_NUMBER: builtins.int
    USER_FIELD_NUMBER: builtins.int
    AUTHENTICATED_FIELD_NUMBER: builtins.int
    TASK_SLICES_FIELD_NUMBER: builtins.int
    SERVICE_ACCOUNT_FIELD_NUMBER: builtins.int
    REALM_FIELD_NUMBER: builtins.int
    RESULTDB_FIELD_NUMBER: builtins.int
    PUBSUB_TOPIC_FIELD_NUMBER: builtins.int
    PUBSUB_USERDATA_FIELD_NUMBER: builtins.int
    BOT_PING_TOLERANCE_SECS_FIELD_NUMBER: builtins.int
    RBE_INSTANCE_FIELD_NUMBER: builtins.int
    task_id: builtins.str
    expiration_secs: builtins.int
    name: builtins.str
    parent_task_id: builtins.str
    priority: builtins.int
    @property
    def properties(self) -> global___TaskProperties:
        """For some amount of time, the properties will be copied into the
        task_slices and vice-versa, to give time to the clients to update.
        Eventually, only task_slices will be supported.
        """
    @property
    def tags(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def created_ts(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    user: builtins.str
    authenticated: builtins.str
    """User name of whoever posted this task, extracted from the credentials."""
    @property
    def task_slices(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TaskSlice]: ...
    service_account: builtins.str
    """Indicates what OAuth2 credentials the task uses when calling other services."""
    realm: builtins.str
    @property
    def resultdb(self) -> global___ResultDBCfg:
        """Configuration of Swarming:ResultDB integration."""
    pubsub_topic: builtins.str
    pubsub_userdata: builtins.str
    bot_ping_tolerance_secs: builtins.int
    rbe_instance: builtins.str
    def __init__(
        self,
        *,
        task_id: builtins.str = ...,
        expiration_secs: builtins.int = ...,
        name: builtins.str = ...,
        parent_task_id: builtins.str = ...,
        priority: builtins.int = ...,
        properties: global___TaskProperties | None = ...,
        tags: collections.abc.Iterable[builtins.str] | None = ...,
        created_ts: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        user: builtins.str = ...,
        authenticated: builtins.str = ...,
        task_slices: collections.abc.Iterable[global___TaskSlice] | None = ...,
        service_account: builtins.str = ...,
        realm: builtins.str = ...,
        resultdb: global___ResultDBCfg | None = ...,
        pubsub_topic: builtins.str = ...,
        pubsub_userdata: builtins.str = ...,
        bot_ping_tolerance_secs: builtins.int = ...,
        rbe_instance: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["created_ts", b"created_ts", "properties", b"properties", "resultdb", b"resultdb"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["authenticated", b"authenticated", "bot_ping_tolerance_secs", b"bot_ping_tolerance_secs", "created_ts", b"created_ts", "expiration_secs", b"expiration_secs", "name", b"name", "parent_task_id", b"parent_task_id", "priority", b"priority", "properties", b"properties", "pubsub_topic", b"pubsub_topic", "pubsub_userdata", b"pubsub_userdata", "rbe_instance", b"rbe_instance", "realm", b"realm", "resultdb", b"resultdb", "service_account", b"service_account", "tags", b"tags", "task_id", b"task_id", "task_slices", b"task_slices", "user", b"user"]) -> None: ...

global___TaskRequestResponse = TaskRequestResponse

@typing_extensions.final
class TaskResultResponse(google.protobuf.message.Message):
    """Representation of the TaskResultSummary or TaskRunResult ndb model."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: builtins.int
    BOT_DIMENSIONS_FIELD_NUMBER: builtins.int
    BOT_ID_FIELD_NUMBER: builtins.int
    BOT_IDLE_SINCE_TS_FIELD_NUMBER: builtins.int
    BOT_VERSION_FIELD_NUMBER: builtins.int
    BOT_LOGS_CLOUD_PROJECT_FIELD_NUMBER: builtins.int
    COMPLETED_TS_FIELD_NUMBER: builtins.int
    COST_SAVED_USD_FIELD_NUMBER: builtins.int
    CREATED_TS_FIELD_NUMBER: builtins.int
    DEDUPED_FROM_FIELD_NUMBER: builtins.int
    DURATION_FIELD_NUMBER: builtins.int
    EXIT_CODE_FIELD_NUMBER: builtins.int
    FAILURE_FIELD_NUMBER: builtins.int
    INTERNAL_FAILURE_FIELD_NUMBER: builtins.int
    MODIFIED_TS_FIELD_NUMBER: builtins.int
    CAS_OUTPUT_ROOT_FIELD_NUMBER: builtins.int
    SERVER_VERSIONS_FIELD_NUMBER: builtins.int
    STARTED_TS_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    ABANDONED_TS_FIELD_NUMBER: builtins.int
    COSTS_USD_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    USER_FIELD_NUMBER: builtins.int
    PERFORMANCE_STATS_FIELD_NUMBER: builtins.int
    CIPD_PINS_FIELD_NUMBER: builtins.int
    RUN_ID_FIELD_NUMBER: builtins.int
    CURRENT_TASK_SLICE_FIELD_NUMBER: builtins.int
    RESULTDB_INFO_FIELD_NUMBER: builtins.int
    MISSING_CAS_FIELD_NUMBER: builtins.int
    MISSING_CIPD_FIELD_NUMBER: builtins.int
    task_id: builtins.str
    """Summary task ID (ending with '0') when creating a new task."""
    @property
    def bot_dimensions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StringListPair]:
        """Time when the task was abandoned instead of normal completion (e.g.
        EXPIRED, BOT_DIED, KILLED).

        The same key cannot be repeated.
        """
    bot_id: builtins.str
    """Unique ID of the bot."""
    @property
    def bot_idle_since_ts(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Time the bot became ready for a next task."""
    bot_version: builtins.str
    """Hash of the bot code which ran the task."""
    bot_logs_cloud_project: builtins.str
    """The cloud project id where the bot saves its logs."""
    @property
    def completed_ts(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Time the task completed normally. Only one of abandoned_ts or completed_ts
        can be set except for state == KILLED.

        In case of KILLED, completed_ts is the time the task completed.
        """
    cost_saved_usd: builtins.float
    """$ saved for task with state DEDUPED."""
    @property
    def created_ts(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Time the task was requested."""
    deduped_from: builtins.str
    """Task ID which results was reused for state DEDUPED."""
    duration: builtins.float
    """Duration of the task in seconds. This excludes overheads."""
    exit_code: builtins.int
    """Process exit code if relevant. May be forcibly set to -1 in exceptional
    cases.
    """
    failure: builtins.bool
    """True if exit_code != 0."""
    internal_failure: builtins.bool
    """True if state is BOT_DIED."""
    @property
    def modified_ts(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Time the results was last updated in the DB."""
    @property
    def cas_output_root(self) -> global___CASReference:
        """CAS Digest of the output root uploaded to RBE-CAS.
        This MUST be digest of [build.bazel.remote.execution.v2.Directory].
        """
    @property
    def server_versions(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Server versions that touched this task."""
    @property
    def started_ts(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Time the task started being run by a bot."""
    state: global___TaskState.ValueType
    """Current state of the task (e.g. PENDING, RUNNING, COMPLETED, EXPIRED, etc)."""
    @property
    def abandoned_ts(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """In the case of KILLED, this records the time the user requested the task to
        stop.
        """
    @property
    def costs_usd(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """Can be multiple values only in TaskResultSummary."""
    name: builtins.str
    """Name of the task. Only set when requesting task ID summary, ending with '0'."""
    @property
    def tags(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Tags associated with the task when it was requested. Only set when
        requesting task ID summary, ending with '0'.
        """
    user: builtins.str
    """User on behalf this task was requested. Only set when requesting task ID
    summary, ending with '0'.
    """
    @property
    def performance_stats(self) -> global___PerformanceStats:
        """Statistics about overhead for an isolated task. Only sent when requested."""
    @property
    def cipd_pins(self) -> global___CipdPins:
        """Listing of the ACTUAL pinned CipdPackages that the task used. These can vary
        from the input packages if the inputs included non-identity versions (e.g. a
        ref like "latest").
        """
    run_id: builtins.str
    """Actual executed task id that this task represents. For deduped tasks, it is
    the same value as deduped_from. This value can be empty if there is no
    execution, for example the task was cancelled.
    """
    current_task_slice: builtins.int
    """Index in the TaskRequest.task_slices (TaskSlice instance) that this result
    represents. This is updated when a TaskSlice is enqueued to run.

    The TaskSlice contains a TaskProperties, which defines what is run.
    """
    @property
    def resultdb_info(self) -> global___ResultDBInfo:
        """ResultDB related information.
        None if the integration was not enabled for this task.
        """
    @property
    def missing_cas(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CASReference]:
        """Reported missing CAS packages on CLIENT_ERROR state"""
    @property
    def missing_cipd(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CipdPackage]:
        """Reported missing CIPD packages on CLIENT_ERROR state"""
    def __init__(
        self,
        *,
        task_id: builtins.str = ...,
        bot_dimensions: collections.abc.Iterable[global___StringListPair] | None = ...,
        bot_id: builtins.str = ...,
        bot_idle_since_ts: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        bot_version: builtins.str = ...,
        bot_logs_cloud_project: builtins.str = ...,
        completed_ts: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        cost_saved_usd: builtins.float = ...,
        created_ts: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        deduped_from: builtins.str = ...,
        duration: builtins.float = ...,
        exit_code: builtins.int = ...,
        failure: builtins.bool = ...,
        internal_failure: builtins.bool = ...,
        modified_ts: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        cas_output_root: global___CASReference | None = ...,
        server_versions: collections.abc.Iterable[builtins.str] | None = ...,
        started_ts: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        state: global___TaskState.ValueType = ...,
        abandoned_ts: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        costs_usd: collections.abc.Iterable[builtins.float] | None = ...,
        name: builtins.str = ...,
        tags: collections.abc.Iterable[builtins.str] | None = ...,
        user: builtins.str = ...,
        performance_stats: global___PerformanceStats | None = ...,
        cipd_pins: global___CipdPins | None = ...,
        run_id: builtins.str = ...,
        current_task_slice: builtins.int = ...,
        resultdb_info: global___ResultDBInfo | None = ...,
        missing_cas: collections.abc.Iterable[global___CASReference] | None = ...,
        missing_cipd: collections.abc.Iterable[global___CipdPackage] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["abandoned_ts", b"abandoned_ts", "bot_idle_since_ts", b"bot_idle_since_ts", "cas_output_root", b"cas_output_root", "cipd_pins", b"cipd_pins", "completed_ts", b"completed_ts", "created_ts", b"created_ts", "modified_ts", b"modified_ts", "performance_stats", b"performance_stats", "resultdb_info", b"resultdb_info", "started_ts", b"started_ts"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["abandoned_ts", b"abandoned_ts", "bot_dimensions", b"bot_dimensions", "bot_id", b"bot_id", "bot_idle_since_ts", b"bot_idle_since_ts", "bot_logs_cloud_project", b"bot_logs_cloud_project", "bot_version", b"bot_version", "cas_output_root", b"cas_output_root", "cipd_pins", b"cipd_pins", "completed_ts", b"completed_ts", "cost_saved_usd", b"cost_saved_usd", "costs_usd", b"costs_usd", "created_ts", b"created_ts", "current_task_slice", b"current_task_slice", "deduped_from", b"deduped_from", "duration", b"duration", "exit_code", b"exit_code", "failure", b"failure", "internal_failure", b"internal_failure", "missing_cas", b"missing_cas", "missing_cipd", b"missing_cipd", "modified_ts", b"modified_ts", "name", b"name", "performance_stats", b"performance_stats", "resultdb_info", b"resultdb_info", "run_id", b"run_id", "server_versions", b"server_versions", "started_ts", b"started_ts", "state", b"state", "tags", b"tags", "task_id", b"task_id", "user", b"user"]) -> None: ...

global___TaskResultResponse = TaskResultResponse

@typing_extensions.final
class TasksCountRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_FIELD_NUMBER: builtins.int
    END_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    @property
    def start(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def end(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    state: global___StateQuery.ValueType
    @property
    def tags(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        start: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        end: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        state: global___StateQuery.ValueType = ...,
        tags: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["end", b"end", "start", b"start"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["end", b"end", "start", b"start", "state", b"state", "tags", b"tags"]) -> None: ...

global___TasksCountRequest = TasksCountRequest

@typing_extensions.final
class TasksCount(google.protobuf.message.Message):
    """Returns the count, as requested."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COUNT_FIELD_NUMBER: builtins.int
    NOW_FIELD_NUMBER: builtins.int
    count: builtins.int
    @property
    def now(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        count: builtins.int = ...,
        now: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["now", b"now"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["count", b"count", "now", b"now"]) -> None: ...

global___TasksCount = TasksCount

@typing_extensions.final
class PerformanceStats(google.protobuf.message.Message):
    """Performance stats of task execution.
    See task_result.PerformanceStats for details.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BOT_OVERHEAD_FIELD_NUMBER: builtins.int
    ISOLATED_DOWNLOAD_FIELD_NUMBER: builtins.int
    ISOLATED_UPLOAD_FIELD_NUMBER: builtins.int
    PACKAGE_INSTALLATION_FIELD_NUMBER: builtins.int
    CACHE_TRIM_FIELD_NUMBER: builtins.int
    NAMED_CACHES_INSTALL_FIELD_NUMBER: builtins.int
    NAMED_CACHES_UNINSTALL_FIELD_NUMBER: builtins.int
    CLEANUP_FIELD_NUMBER: builtins.int
    bot_overhead: builtins.float
    @property
    def isolated_download(self) -> global___CASOperationStats: ...
    @property
    def isolated_upload(self) -> global___CASOperationStats: ...
    @property
    def package_installation(self) -> global___OperationStats: ...
    @property
    def cache_trim(self) -> global___OperationStats: ...
    @property
    def named_caches_install(self) -> global___OperationStats: ...
    @property
    def named_caches_uninstall(self) -> global___OperationStats: ...
    @property
    def cleanup(self) -> global___OperationStats: ...
    def __init__(
        self,
        *,
        bot_overhead: builtins.float = ...,
        isolated_download: global___CASOperationStats | None = ...,
        isolated_upload: global___CASOperationStats | None = ...,
        package_installation: global___OperationStats | None = ...,
        cache_trim: global___OperationStats | None = ...,
        named_caches_install: global___OperationStats | None = ...,
        named_caches_uninstall: global___OperationStats | None = ...,
        cleanup: global___OperationStats | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["cache_trim", b"cache_trim", "cleanup", b"cleanup", "isolated_download", b"isolated_download", "isolated_upload", b"isolated_upload", "named_caches_install", b"named_caches_install", "named_caches_uninstall", b"named_caches_uninstall", "package_installation", b"package_installation"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bot_overhead", b"bot_overhead", "cache_trim", b"cache_trim", "cleanup", b"cleanup", "isolated_download", b"isolated_download", "isolated_upload", b"isolated_upload", "named_caches_install", b"named_caches_install", "named_caches_uninstall", b"named_caches_uninstall", "package_installation", b"package_installation"]) -> None: ...

global___PerformanceStats = PerformanceStats

@typing_extensions.final
class OperationStats(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DURATION_FIELD_NUMBER: builtins.int
    duration: builtins.float
    """Duration in seconds."""
    def __init__(
        self,
        *,
        duration: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["duration", b"duration"]) -> None: ...

global___OperationStats = OperationStats

@typing_extensions.final
class CASOperationStats(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DURATION_FIELD_NUMBER: builtins.int
    INITIAL_NUMBER_ITEMS_FIELD_NUMBER: builtins.int
    INITIAL_SIZE_FIELD_NUMBER: builtins.int
    ITEMS_COLD_FIELD_NUMBER: builtins.int
    ITEMS_HOT_FIELD_NUMBER: builtins.int
    NUM_ITEMS_COLD_FIELD_NUMBER: builtins.int
    TOTAL_BYTES_ITEMS_COLD_FIELD_NUMBER: builtins.int
    NUM_ITEMS_HOT_FIELD_NUMBER: builtins.int
    TOTAL_BYTES_ITEMS_HOT_FIELD_NUMBER: builtins.int
    duration: builtins.float
    """Duration in seconds."""
    initial_number_items: builtins.int
    initial_size: builtins.int
    items_cold: builtins.bytes
    """These buffers are compressed as deflate'd delta-encoded varints. They are
    all the items for an isolated operation, which can scale in the 100k range.
    So can be large! See //client/utils/large.py for the code to handle these.
    """
    items_hot: builtins.bytes
    num_items_cold: builtins.int
    """Corresponding summaries; for each list above, sum of the number of files
    and the sum bytes of the files.
    """
    total_bytes_items_cold: builtins.int
    num_items_hot: builtins.int
    total_bytes_items_hot: builtins.int
    def __init__(
        self,
        *,
        duration: builtins.float = ...,
        initial_number_items: builtins.int = ...,
        initial_size: builtins.int = ...,
        items_cold: builtins.bytes = ...,
        items_hot: builtins.bytes = ...,
        num_items_cold: builtins.int = ...,
        total_bytes_items_cold: builtins.int = ...,
        num_items_hot: builtins.int = ...,
        total_bytes_items_hot: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["duration", b"duration", "initial_number_items", b"initial_number_items", "initial_size", b"initial_size", "items_cold", b"items_cold", "items_hot", b"items_hot", "num_items_cold", b"num_items_cold", "num_items_hot", b"num_items_hot", "total_bytes_items_cold", b"total_bytes_items_cold", "total_bytes_items_hot", b"total_bytes_items_hot"]) -> None: ...

global___CASOperationStats = CASOperationStats
