# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2023 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.cloud.datastore_v1.proto.entity_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ErrorType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ErrorTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ErrorType.ValueType], builtins.type):  # noqa: F821
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NO_ERROR: _ErrorType.ValueType  # 0
    ANALYZE_BUILD_SETUP: _ErrorType.ValueType  # 1
    ANALYZE_NO_CRASH: _ErrorType.ValueType  # 2
    ANALYZE_NO_REVISIONS_LIST: _ErrorType.ValueType  # 3
    ANALYZE_NO_REVISION_INDEX: _ErrorType.ValueType  # 4
    TESTCASE_SETUP: _ErrorType.ValueType  # 5
    UNHANDLED: _ErrorType.ValueType  # 6
    VARIANT_BUILD_SETUP: _ErrorType.ValueType  # 7
    MINIMIZE_SETUP: _ErrorType.ValueType  # 8
    FUZZ_BUILD_SETUP_FAILURE: _ErrorType.ValueType  # 9
    FUZZ_DATA_BUNDLE_SETUP_FAILURE: _ErrorType.ValueType  # 10
    FUZZ_NO_FUZZER: _ErrorType.ValueType  # 11
    PROGRESSION_REVISION_LIST_ERROR: _ErrorType.ValueType  # 12
    PROGRESSION_BUILD_NOT_FOUND: _ErrorType.ValueType  # 13
    PROGRESSION_NO_CRASH: _ErrorType.ValueType  # 14
    PROGRESSION_BAD_STATE_MIN_MAX: _ErrorType.ValueType  # 15
    PROGRESSION_TIMEOUT: _ErrorType.ValueType  # 16
    PROGRESSION_BAD_BUILD: _ErrorType.ValueType  # 17
    PROGRESSION_BUILD_SETUP_ERROR: _ErrorType.ValueType  # 18
    REGRESSION_REVISION_LIST_ERROR: _ErrorType.ValueType  # 19

class ErrorType(_ErrorType, metaclass=_ErrorTypeEnumTypeWrapper): ...

NO_ERROR: ErrorType.ValueType  # 0
ANALYZE_BUILD_SETUP: ErrorType.ValueType  # 1
ANALYZE_NO_CRASH: ErrorType.ValueType  # 2
ANALYZE_NO_REVISIONS_LIST: ErrorType.ValueType  # 3
ANALYZE_NO_REVISION_INDEX: ErrorType.ValueType  # 4
TESTCASE_SETUP: ErrorType.ValueType  # 5
UNHANDLED: ErrorType.ValueType  # 6
VARIANT_BUILD_SETUP: ErrorType.ValueType  # 7
MINIMIZE_SETUP: ErrorType.ValueType  # 8
FUZZ_BUILD_SETUP_FAILURE: ErrorType.ValueType  # 9
FUZZ_DATA_BUNDLE_SETUP_FAILURE: ErrorType.ValueType  # 10
FUZZ_NO_FUZZER: ErrorType.ValueType  # 11
PROGRESSION_REVISION_LIST_ERROR: ErrorType.ValueType  # 12
PROGRESSION_BUILD_NOT_FOUND: ErrorType.ValueType  # 13
PROGRESSION_NO_CRASH: ErrorType.ValueType  # 14
PROGRESSION_BAD_STATE_MIN_MAX: ErrorType.ValueType  # 15
PROGRESSION_TIMEOUT: ErrorType.ValueType  # 16
PROGRESSION_BAD_BUILD: ErrorType.ValueType  # 17
PROGRESSION_BUILD_SETUP_ERROR: ErrorType.ValueType  # 18
REGRESSION_REVISION_LIST_ERROR: ErrorType.ValueType  # 19
global___ErrorType = ErrorType

class Json(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERIALIZED_FIELD_NUMBER: builtins.int
    serialized: builtins.str
    def __init__(
        self,
        *,
        serialized: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["serialized", b"serialized"]) -> None: ...

global___Json = Json

class UworkerEntityWrapper(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTITY_FIELD_NUMBER: builtins.int
    CHANGED_FIELD_NUMBER: builtins.int
    @property
    def entity(self) -> google.cloud.datastore_v1.proto.entity_pb2.Entity: ...
    @property
    def changed(self) -> global___Json: ...
    def __init__(
        self,
        *,
        entity: google.cloud.datastore_v1.proto.entity_pb2.Entity | None = ...,
        changed: global___Json | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["changed", b"changed", "entity", b"entity"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["changed", b"changed", "entity", b"entity"]) -> None: ...

global___UworkerEntityWrapper = UworkerEntityWrapper

class SetupInput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FUZZER_FIELD_NUMBER: builtins.int
    FUZZER_NAME_FIELD_NUMBER: builtins.int
    DATA_BUNDLES_FIELD_NUMBER: builtins.int
    FUZZER_LOG_UPLOAD_URL_FIELD_NUMBER: builtins.int
    FUZZER_DOWNLOAD_URL_FIELD_NUMBER: builtins.int
    TESTCASE_DOWNLOAD_URL_FIELD_NUMBER: builtins.int
    @property
    def fuzzer(self) -> google.cloud.datastore_v1.proto.entity_pb2.Entity: ...
    fuzzer_name: builtins.str
    @property
    def data_bundles(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.cloud.datastore_v1.proto.entity_pb2.Entity]: ...
    fuzzer_log_upload_url: builtins.str
    fuzzer_download_url: builtins.str
    testcase_download_url: builtins.str
    def __init__(
        self,
        *,
        fuzzer: google.cloud.datastore_v1.proto.entity_pb2.Entity | None = ...,
        fuzzer_name: builtins.str | None = ...,
        data_bundles: collections.abc.Iterable[google.cloud.datastore_v1.proto.entity_pb2.Entity] | None = ...,
        fuzzer_log_upload_url: builtins.str | None = ...,
        fuzzer_download_url: builtins.str | None = ...,
        testcase_download_url: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_fuzzer", b"_fuzzer", "_fuzzer_download_url", b"_fuzzer_download_url", "_fuzzer_log_upload_url", b"_fuzzer_log_upload_url", "_fuzzer_name", b"_fuzzer_name", "_testcase_download_url", b"_testcase_download_url", "fuzzer", b"fuzzer", "fuzzer_download_url", b"fuzzer_download_url", "fuzzer_log_upload_url", b"fuzzer_log_upload_url", "fuzzer_name", b"fuzzer_name", "testcase_download_url", b"testcase_download_url"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_fuzzer", b"_fuzzer", "_fuzzer_download_url", b"_fuzzer_download_url", "_fuzzer_log_upload_url", b"_fuzzer_log_upload_url", "_fuzzer_name", b"_fuzzer_name", "_testcase_download_url", b"_testcase_download_url", "data_bundles", b"data_bundles", "fuzzer", b"fuzzer", "fuzzer_download_url", b"fuzzer_download_url", "fuzzer_log_upload_url", b"fuzzer_log_upload_url", "fuzzer_name", b"fuzzer_name", "testcase_download_url", b"testcase_download_url"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_fuzzer", b"_fuzzer"]) -> typing_extensions.Literal["fuzzer"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_fuzzer_download_url", b"_fuzzer_download_url"]) -> typing_extensions.Literal["fuzzer_download_url"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_fuzzer_log_upload_url", b"_fuzzer_log_upload_url"]) -> typing_extensions.Literal["fuzzer_log_upload_url"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_fuzzer_name", b"_fuzzer_name"]) -> typing_extensions.Literal["fuzzer_name"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_testcase_download_url", b"_testcase_download_url"]) -> typing_extensions.Literal["testcase_download_url"] | None: ...

global___SetupInput = SetupInput

class AnalyzeTaskInput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BAD_REVISIONS_FIELD_NUMBER: builtins.int
    @property
    def bad_revisions(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        bad_revisions: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["bad_revisions", b"bad_revisions"]) -> None: ...

global___AnalyzeTaskInput = AnalyzeTaskInput

class SymbolizeTaskInput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___SymbolizeTaskInput = SymbolizeTaskInput

class FuzzTaskInput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TARGETS_COUNT_FIELD_NUMBER: builtins.int
    @property
    def targets_count(self) -> google.cloud.datastore_v1.proto.entity_pb2.Entity: ...
    def __init__(
        self,
        *,
        targets_count: google.cloud.datastore_v1.proto.entity_pb2.Entity | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_targets_count", b"_targets_count", "targets_count", b"targets_count"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_targets_count", b"_targets_count", "targets_count", b"targets_count"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_targets_count", b"_targets_count"]) -> typing_extensions.Literal["targets_count"] | None: ...

global___FuzzTaskInput = FuzzTaskInput

class MinimizeTaskInput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TESTCASE_UPLOAD_URL_FIELD_NUMBER: builtins.int
    testcase_upload_url: builtins.str
    """TODO(pgrace): Finish this."""
    def __init__(
        self,
        *,
        testcase_upload_url: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_testcase_upload_url", b"_testcase_upload_url", "testcase_upload_url", b"testcase_upload_url"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_testcase_upload_url", b"_testcase_upload_url", "testcase_upload_url", b"testcase_upload_url"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_testcase_upload_url", b"_testcase_upload_url"]) -> typing_extensions.Literal["testcase_upload_url"] | None: ...

global___MinimizeTaskInput = MinimizeTaskInput

class RegressionTaskInput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BAD_REVISIONS_FIELD_NUMBER: builtins.int
    @property
    def bad_revisions(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        bad_revisions: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["bad_revisions", b"bad_revisions"]) -> None: ...

global___RegressionTaskInput = RegressionTaskInput

class ProgressionTaskInput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CUSTOM_BINARY_FIELD_NUMBER: builtins.int
    BAD_REVISIONS_FIELD_NUMBER: builtins.int
    custom_binary: builtins.bool
    @property
    def bad_revisions(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        custom_binary: builtins.bool | None = ...,
        bad_revisions: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_custom_binary", b"_custom_binary", "custom_binary", b"custom_binary"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_custom_binary", b"_custom_binary", "bad_revisions", b"bad_revisions", "custom_binary", b"custom_binary"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_custom_binary", b"_custom_binary"]) -> typing_extensions.Literal["custom_binary"] | None: ...

global___ProgressionTaskInput = ProgressionTaskInput

class CorpusPruningTaskInput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FUZZ_TARGET_FIELD_NUMBER: builtins.int
    LAST_EXECUTION_FAILED_FIELD_NUMBER: builtins.int
    @property
    def fuzz_target(self) -> google.cloud.datastore_v1.proto.entity_pb2.Entity: ...
    last_execution_failed: builtins.bool
    def __init__(
        self,
        *,
        fuzz_target: google.cloud.datastore_v1.proto.entity_pb2.Entity | None = ...,
        last_execution_failed: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_fuzz_target", b"_fuzz_target", "_last_execution_failed", b"_last_execution_failed", "fuzz_target", b"fuzz_target", "last_execution_failed", b"last_execution_failed"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_fuzz_target", b"_fuzz_target", "_last_execution_failed", b"_last_execution_failed", "fuzz_target", b"fuzz_target", "last_execution_failed", b"last_execution_failed"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_fuzz_target", b"_fuzz_target"]) -> typing_extensions.Literal["fuzz_target"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_last_execution_failed", b"_last_execution_failed"]) -> typing_extensions.Literal["last_execution_failed"] | None: ...

global___CorpusPruningTaskInput = CorpusPruningTaskInput

class Input(google.protobuf.message.Message):
    """TODO(metzman): Handle None in protobuf. Right now, it's hard to tell if a
    field was unset or set to None.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TESTCASE_FIELD_NUMBER: builtins.int
    TESTCASE_UPLOAD_METADATA_FIELD_NUMBER: builtins.int
    TESTCASE_ID_FIELD_NUMBER: builtins.int
    UWORKER_ENV_FIELD_NUMBER: builtins.int
    JOB_TYPE_FIELD_NUMBER: builtins.int
    UWORKER_OUTPUT_UPLOAD_URL_FIELD_NUMBER: builtins.int
    VARIANT_FIELD_NUMBER: builtins.int
    ORIGINAL_JOB_TYPE_FIELD_NUMBER: builtins.int
    FUZZER_NAME_FIELD_NUMBER: builtins.int
    SETUP_INPUT_FIELD_NUMBER: builtins.int
    ANALYZE_TASK_INPUT_FIELD_NUMBER: builtins.int
    CORPUS_PRUNING_TASK_INPUT_FIELD_NUMBER: builtins.int
    FUZZ_TASK_INPUT_FIELD_NUMBER: builtins.int
    MINIMIZE_TASK_INPUT_FIELD_NUMBER: builtins.int
    PROGRESSION_TASK_INPUT_FIELD_NUMBER: builtins.int
    REGRESSION_TASK_INPUT_FIELD_NUMBER: builtins.int
    SYMBOLIZE_TASK_INPUT_FIELD_NUMBER: builtins.int
    MODULE_NAME_FIELD_NUMBER: builtins.int
    @property
    def testcase(self) -> google.cloud.datastore_v1.proto.entity_pb2.Entity: ...
    @property
    def testcase_upload_metadata(self) -> google.cloud.datastore_v1.proto.entity_pb2.Entity: ...
    testcase_id: builtins.str
    @property
    def uworker_env(self) -> global___Json: ...
    job_type: builtins.str
    uworker_output_upload_url: builtins.str
    """uworker_io is the only module that should be using this."""
    @property
    def variant(self) -> google.cloud.datastore_v1.proto.entity_pb2.Entity: ...
    original_job_type: builtins.str
    fuzzer_name: builtins.str
    @property
    def setup_input(self) -> global___SetupInput: ...
    @property
    def analyze_task_input(self) -> global___AnalyzeTaskInput: ...
    @property
    def corpus_pruning_task_input(self) -> global___CorpusPruningTaskInput: ...
    @property
    def fuzz_task_input(self) -> global___FuzzTaskInput: ...
    @property
    def minimize_task_input(self) -> global___MinimizeTaskInput: ...
    @property
    def progression_task_input(self) -> global___ProgressionTaskInput: ...
    @property
    def regression_task_input(self) -> global___RegressionTaskInput: ...
    @property
    def symbolize_task_input(self) -> global___SymbolizeTaskInput: ...
    module_name: builtins.str
    def __init__(
        self,
        *,
        testcase: google.cloud.datastore_v1.proto.entity_pb2.Entity | None = ...,
        testcase_upload_metadata: google.cloud.datastore_v1.proto.entity_pb2.Entity | None = ...,
        testcase_id: builtins.str | None = ...,
        uworker_env: global___Json | None = ...,
        job_type: builtins.str | None = ...,
        uworker_output_upload_url: builtins.str | None = ...,
        variant: google.cloud.datastore_v1.proto.entity_pb2.Entity | None = ...,
        original_job_type: builtins.str | None = ...,
        fuzzer_name: builtins.str | None = ...,
        setup_input: global___SetupInput | None = ...,
        analyze_task_input: global___AnalyzeTaskInput | None = ...,
        corpus_pruning_task_input: global___CorpusPruningTaskInput | None = ...,
        fuzz_task_input: global___FuzzTaskInput | None = ...,
        minimize_task_input: global___MinimizeTaskInput | None = ...,
        progression_task_input: global___ProgressionTaskInput | None = ...,
        regression_task_input: global___RegressionTaskInput | None = ...,
        symbolize_task_input: global___SymbolizeTaskInput | None = ...,
        module_name: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_analyze_task_input", b"_analyze_task_input", "_corpus_pruning_task_input", b"_corpus_pruning_task_input", "_fuzz_task_input", b"_fuzz_task_input", "_fuzzer_name", b"_fuzzer_name", "_job_type", b"_job_type", "_minimize_task_input", b"_minimize_task_input", "_module_name", b"_module_name", "_original_job_type", b"_original_job_type", "_progression_task_input", b"_progression_task_input", "_regression_task_input", b"_regression_task_input", "_setup_input", b"_setup_input", "_symbolize_task_input", b"_symbolize_task_input", "_testcase", b"_testcase", "_testcase_id", b"_testcase_id", "_testcase_upload_metadata", b"_testcase_upload_metadata", "_uworker_env", b"_uworker_env", "_uworker_output_upload_url", b"_uworker_output_upload_url", "_variant", b"_variant", "analyze_task_input", b"analyze_task_input", "corpus_pruning_task_input", b"corpus_pruning_task_input", "fuzz_task_input", b"fuzz_task_input", "fuzzer_name", b"fuzzer_name", "job_type", b"job_type", "minimize_task_input", b"minimize_task_input", "module_name", b"module_name", "original_job_type", b"original_job_type", "progression_task_input", b"progression_task_input", "regression_task_input", b"regression_task_input", "setup_input", b"setup_input", "symbolize_task_input", b"symbolize_task_input", "testcase", b"testcase", "testcase_id", b"testcase_id", "testcase_upload_metadata", b"testcase_upload_metadata", "uworker_env", b"uworker_env", "uworker_output_upload_url", b"uworker_output_upload_url", "variant", b"variant"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_analyze_task_input", b"_analyze_task_input", "_corpus_pruning_task_input", b"_corpus_pruning_task_input", "_fuzz_task_input", b"_fuzz_task_input", "_fuzzer_name", b"_fuzzer_name", "_job_type", b"_job_type", "_minimize_task_input", b"_minimize_task_input", "_module_name", b"_module_name", "_original_job_type", b"_original_job_type", "_progression_task_input", b"_progression_task_input", "_regression_task_input", b"_regression_task_input", "_setup_input", b"_setup_input", "_symbolize_task_input", b"_symbolize_task_input", "_testcase", b"_testcase", "_testcase_id", b"_testcase_id", "_testcase_upload_metadata", b"_testcase_upload_metadata", "_uworker_env", b"_uworker_env", "_uworker_output_upload_url", b"_uworker_output_upload_url", "_variant", b"_variant", "analyze_task_input", b"analyze_task_input", "corpus_pruning_task_input", b"corpus_pruning_task_input", "fuzz_task_input", b"fuzz_task_input", "fuzzer_name", b"fuzzer_name", "job_type", b"job_type", "minimize_task_input", b"minimize_task_input", "module_name", b"module_name", "original_job_type", b"original_job_type", "progression_task_input", b"progression_task_input", "regression_task_input", b"regression_task_input", "setup_input", b"setup_input", "symbolize_task_input", b"symbolize_task_input", "testcase", b"testcase", "testcase_id", b"testcase_id", "testcase_upload_metadata", b"testcase_upload_metadata", "uworker_env", b"uworker_env", "uworker_output_upload_url", b"uworker_output_upload_url", "variant", b"variant"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_analyze_task_input", b"_analyze_task_input"]) -> typing_extensions.Literal["analyze_task_input"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_corpus_pruning_task_input", b"_corpus_pruning_task_input"]) -> typing_extensions.Literal["corpus_pruning_task_input"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_fuzz_task_input", b"_fuzz_task_input"]) -> typing_extensions.Literal["fuzz_task_input"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_fuzzer_name", b"_fuzzer_name"]) -> typing_extensions.Literal["fuzzer_name"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_job_type", b"_job_type"]) -> typing_extensions.Literal["job_type"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_minimize_task_input", b"_minimize_task_input"]) -> typing_extensions.Literal["minimize_task_input"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_module_name", b"_module_name"]) -> typing_extensions.Literal["module_name"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_original_job_type", b"_original_job_type"]) -> typing_extensions.Literal["original_job_type"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_progression_task_input", b"_progression_task_input"]) -> typing_extensions.Literal["progression_task_input"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_regression_task_input", b"_regression_task_input"]) -> typing_extensions.Literal["regression_task_input"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_setup_input", b"_setup_input"]) -> typing_extensions.Literal["setup_input"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_symbolize_task_input", b"_symbolize_task_input"]) -> typing_extensions.Literal["symbolize_task_input"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_testcase", b"_testcase"]) -> typing_extensions.Literal["testcase"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_testcase_id", b"_testcase_id"]) -> typing_extensions.Literal["testcase_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_testcase_upload_metadata", b"_testcase_upload_metadata"]) -> typing_extensions.Literal["testcase_upload_metadata"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_uworker_env", b"_uworker_env"]) -> typing_extensions.Literal["uworker_env"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_uworker_output_upload_url", b"_uworker_output_upload_url"]) -> typing_extensions.Literal["uworker_output_upload_url"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_variant", b"_variant"]) -> typing_extensions.Literal["variant"] | None: ...

global___Input = Input

class SymbolizeTaskOutput(google.protobuf.message.Message):
    """TODO(metzman): Fill this out."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___SymbolizeTaskOutput = SymbolizeTaskOutput

class AnalyzeTaskOutput(google.protobuf.message.Message):
    """TODO(metzman): Fill this out."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___AnalyzeTaskOutput = AnalyzeTaskOutput

class FuzzTaskOutput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FUZZER_NAME_FIELD_NUMBER: builtins.int
    CRASH_REVISION_FIELD_NUMBER: builtins.int
    JOB_RUN_TIMESTAMP_FIELD_NUMBER: builtins.int
    NEW_CRASH_COUNT_FIELD_NUMBER: builtins.int
    KNOWN_CRASH_COUNT_FIELD_NUMBER: builtins.int
    TESTCASES_EXECUTED_FIELD_NUMBER: builtins.int
    JOB_RUN_CRASHES_FIELD_NUMBER: builtins.int
    FULLY_QUALIFIED_FUZZER_NAME_FIELD_NUMBER: builtins.int
    NEW_TARGETS_COUNT_FIELD_NUMBER: builtins.int
    fuzzer_name: builtins.str
    crash_revision: builtins.str
    job_run_timestamp: builtins.float
    new_crash_count: builtins.int
    known_crash_count: builtins.int
    testcases_executed: builtins.int
    @property
    def job_run_crashes(self) -> global___Json: ...
    fully_qualified_fuzzer_name: builtins.str
    new_targets_count: builtins.int
    def __init__(
        self,
        *,
        fuzzer_name: builtins.str | None = ...,
        crash_revision: builtins.str | None = ...,
        job_run_timestamp: builtins.float | None = ...,
        new_crash_count: builtins.int | None = ...,
        known_crash_count: builtins.int | None = ...,
        testcases_executed: builtins.int | None = ...,
        job_run_crashes: global___Json | None = ...,
        fully_qualified_fuzzer_name: builtins.str | None = ...,
        new_targets_count: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_crash_revision", b"_crash_revision", "_fully_qualified_fuzzer_name", b"_fully_qualified_fuzzer_name", "_fuzzer_name", b"_fuzzer_name", "_job_run_crashes", b"_job_run_crashes", "_job_run_timestamp", b"_job_run_timestamp", "_known_crash_count", b"_known_crash_count", "_new_crash_count", b"_new_crash_count", "_new_targets_count", b"_new_targets_count", "_testcases_executed", b"_testcases_executed", "crash_revision", b"crash_revision", "fully_qualified_fuzzer_name", b"fully_qualified_fuzzer_name", "fuzzer_name", b"fuzzer_name", "job_run_crashes", b"job_run_crashes", "job_run_timestamp", b"job_run_timestamp", "known_crash_count", b"known_crash_count", "new_crash_count", b"new_crash_count", "new_targets_count", b"new_targets_count", "testcases_executed", b"testcases_executed"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_crash_revision", b"_crash_revision", "_fully_qualified_fuzzer_name", b"_fully_qualified_fuzzer_name", "_fuzzer_name", b"_fuzzer_name", "_job_run_crashes", b"_job_run_crashes", "_job_run_timestamp", b"_job_run_timestamp", "_known_crash_count", b"_known_crash_count", "_new_crash_count", b"_new_crash_count", "_new_targets_count", b"_new_targets_count", "_testcases_executed", b"_testcases_executed", "crash_revision", b"crash_revision", "fully_qualified_fuzzer_name", b"fully_qualified_fuzzer_name", "fuzzer_name", b"fuzzer_name", "job_run_crashes", b"job_run_crashes", "job_run_timestamp", b"job_run_timestamp", "known_crash_count", b"known_crash_count", "new_crash_count", b"new_crash_count", "new_targets_count", b"new_targets_count", "testcases_executed", b"testcases_executed"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_crash_revision", b"_crash_revision"]) -> typing_extensions.Literal["crash_revision"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_fully_qualified_fuzzer_name", b"_fully_qualified_fuzzer_name"]) -> typing_extensions.Literal["fully_qualified_fuzzer_name"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_fuzzer_name", b"_fuzzer_name"]) -> typing_extensions.Literal["fuzzer_name"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_job_run_crashes", b"_job_run_crashes"]) -> typing_extensions.Literal["job_run_crashes"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_job_run_timestamp", b"_job_run_timestamp"]) -> typing_extensions.Literal["job_run_timestamp"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_known_crash_count", b"_known_crash_count"]) -> typing_extensions.Literal["known_crash_count"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_new_crash_count", b"_new_crash_count"]) -> typing_extensions.Literal["new_crash_count"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_new_targets_count", b"_new_targets_count"]) -> typing_extensions.Literal["new_targets_count"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_testcases_executed", b"_testcases_executed"]) -> typing_extensions.Literal["testcases_executed"] | None: ...

global___FuzzTaskOutput = FuzzTaskOutput

class MinimizeTaskOutput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LAST_CRASH_RESULT_DICT_FIELD_NUMBER: builtins.int
    FLAKY_STACK_FIELD_NUMBER: builtins.int
    BUILD_FAIL_WAIT_FIELD_NUMBER: builtins.int
    @property
    def last_crash_result_dict(self) -> global___Json: ...
    flaky_stack: builtins.bool
    build_fail_wait: builtins.int
    def __init__(
        self,
        *,
        last_crash_result_dict: global___Json | None = ...,
        flaky_stack: builtins.bool | None = ...,
        build_fail_wait: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_build_fail_wait", b"_build_fail_wait", "_flaky_stack", b"_flaky_stack", "_last_crash_result_dict", b"_last_crash_result_dict", "build_fail_wait", b"build_fail_wait", "flaky_stack", b"flaky_stack", "last_crash_result_dict", b"last_crash_result_dict"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_build_fail_wait", b"_build_fail_wait", "_flaky_stack", b"_flaky_stack", "_last_crash_result_dict", b"_last_crash_result_dict", "build_fail_wait", b"build_fail_wait", "flaky_stack", b"flaky_stack", "last_crash_result_dict", b"last_crash_result_dict"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_build_fail_wait", b"_build_fail_wait"]) -> typing_extensions.Literal["build_fail_wait"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_flaky_stack", b"_flaky_stack"]) -> typing_extensions.Literal["flaky_stack"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_last_crash_result_dict", b"_last_crash_result_dict"]) -> typing_extensions.Literal["last_crash_result_dict"] | None: ...

global___MinimizeTaskOutput = MinimizeTaskOutput

class RegressionTaskOutput(google.protobuf.message.Message):
    """TODO(https://github.com/google/clusterfuzz/issues/3008): Fill this in."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___RegressionTaskOutput = RegressionTaskOutput

class BuildData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IS_BAD_BUILD_FIELD_NUMBER: builtins.int
    SHOULD_IGNORE_CRASH_RESULT_FIELD_NUMBER: builtins.int
    BUILD_RUN_CONSOLE_OUTPUT_FIELD_NUMBER: builtins.int
    is_bad_build: builtins.bool
    should_ignore_crash_result: builtins.bool
    build_run_console_output: builtins.str
    def __init__(
        self,
        *,
        is_bad_build: builtins.bool | None = ...,
        should_ignore_crash_result: builtins.bool | None = ...,
        build_run_console_output: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_build_run_console_output", b"_build_run_console_output", "_is_bad_build", b"_is_bad_build", "_should_ignore_crash_result", b"_should_ignore_crash_result", "build_run_console_output", b"build_run_console_output", "is_bad_build", b"is_bad_build", "should_ignore_crash_result", b"should_ignore_crash_result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_build_run_console_output", b"_build_run_console_output", "_is_bad_build", b"_is_bad_build", "_should_ignore_crash_result", b"_should_ignore_crash_result", "build_run_console_output", b"build_run_console_output", "is_bad_build", b"is_bad_build", "should_ignore_crash_result", b"should_ignore_crash_result"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_build_run_console_output", b"_build_run_console_output"]) -> typing_extensions.Literal["build_run_console_output"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_is_bad_build", b"_is_bad_build"]) -> typing_extensions.Literal["is_bad_build"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_should_ignore_crash_result", b"_should_ignore_crash_result"]) -> typing_extensions.Literal["should_ignore_crash_result"] | None: ...

global___BuildData = BuildData

class ProgressionTaskOutput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MIN_REVISION_FIELD_NUMBER: builtins.int
    MAX_REVISION_FIELD_NUMBER: builtins.int
    CRASH_ON_LATEST_FIELD_NUMBER: builtins.int
    CRASH_ON_LATEST_MESSAGE_FIELD_NUMBER: builtins.int
    CRASH_REVISION_FIELD_NUMBER: builtins.int
    LAST_TESTED_CRASH_STACKTRACE_FIELD_NUMBER: builtins.int
    LAST_PROGRESSION_MIN_FIELD_NUMBER: builtins.int
    LAST_PROGRESSION_MAX_FIELD_NUMBER: builtins.int
    CLEAR_MIN_MAX_METADATA_FIELD_NUMBER: builtins.int
    min_revision: builtins.int
    max_revision: builtins.int
    crash_on_latest: builtins.bool
    """Set to true when latest revision or latest custom build still crash."""
    crash_on_latest_message: builtins.str
    crash_revision: builtins.int
    """Information passed back to trusted worker when we crash on latest."""
    last_tested_crash_stacktrace: builtins.str
    last_progression_min: builtins.int
    last_progression_max: builtins.int
    clear_min_max_metadata: builtins.bool
    """When set to True, we delete the metadata related to: last_progression_min
    and last_progression_max from the testcase on postprocess.
    """
    def __init__(
        self,
        *,
        min_revision: builtins.int | None = ...,
        max_revision: builtins.int | None = ...,
        crash_on_latest: builtins.bool | None = ...,
        crash_on_latest_message: builtins.str | None = ...,
        crash_revision: builtins.int | None = ...,
        last_tested_crash_stacktrace: builtins.str | None = ...,
        last_progression_min: builtins.int | None = ...,
        last_progression_max: builtins.int | None = ...,
        clear_min_max_metadata: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_clear_min_max_metadata", b"_clear_min_max_metadata", "_crash_on_latest", b"_crash_on_latest", "_crash_on_latest_message", b"_crash_on_latest_message", "_crash_revision", b"_crash_revision", "_last_progression_max", b"_last_progression_max", "_last_progression_min", b"_last_progression_min", "_last_tested_crash_stacktrace", b"_last_tested_crash_stacktrace", "_max_revision", b"_max_revision", "_min_revision", b"_min_revision", "clear_min_max_metadata", b"clear_min_max_metadata", "crash_on_latest", b"crash_on_latest", "crash_on_latest_message", b"crash_on_latest_message", "crash_revision", b"crash_revision", "last_progression_max", b"last_progression_max", "last_progression_min", b"last_progression_min", "last_tested_crash_stacktrace", b"last_tested_crash_stacktrace", "max_revision", b"max_revision", "min_revision", b"min_revision"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_clear_min_max_metadata", b"_clear_min_max_metadata", "_crash_on_latest", b"_crash_on_latest", "_crash_on_latest_message", b"_crash_on_latest_message", "_crash_revision", b"_crash_revision", "_last_progression_max", b"_last_progression_max", "_last_progression_min", b"_last_progression_min", "_last_tested_crash_stacktrace", b"_last_tested_crash_stacktrace", "_max_revision", b"_max_revision", "_min_revision", b"_min_revision", "clear_min_max_metadata", b"clear_min_max_metadata", "crash_on_latest", b"crash_on_latest", "crash_on_latest_message", b"crash_on_latest_message", "crash_revision", b"crash_revision", "last_progression_max", b"last_progression_max", "last_progression_min", b"last_progression_min", "last_tested_crash_stacktrace", b"last_tested_crash_stacktrace", "max_revision", b"max_revision", "min_revision", b"min_revision"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_clear_min_max_metadata", b"_clear_min_max_metadata"]) -> typing_extensions.Literal["clear_min_max_metadata"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_crash_on_latest", b"_crash_on_latest"]) -> typing_extensions.Literal["crash_on_latest"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_crash_on_latest_message", b"_crash_on_latest_message"]) -> typing_extensions.Literal["crash_on_latest_message"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_crash_revision", b"_crash_revision"]) -> typing_extensions.Literal["crash_revision"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_last_progression_max", b"_last_progression_max"]) -> typing_extensions.Literal["last_progression_max"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_last_progression_min", b"_last_progression_min"]) -> typing_extensions.Literal["last_progression_min"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_last_tested_crash_stacktrace", b"_last_tested_crash_stacktrace"]) -> typing_extensions.Literal["last_tested_crash_stacktrace"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_max_revision", b"_max_revision"]) -> typing_extensions.Literal["max_revision"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_min_revision", b"_min_revision"]) -> typing_extensions.Literal["min_revision"] | None: ...

global___ProgressionTaskOutput = ProgressionTaskOutput

class Output(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TESTCASE_FIELD_NUMBER: builtins.int
    TESTCASE_UPLOAD_METADATA_FIELD_NUMBER: builtins.int
    VARIANT_FIELD_NUMBER: builtins.int
    ERROR_TYPE_FIELD_NUMBER: builtins.int
    UWORKER_INPUT_FIELD_NUMBER: builtins.int
    TEST_TIMEOUT_FIELD_NUMBER: builtins.int
    CRASH_TIME_FIELD_NUMBER: builtins.int
    CRASH_STACKTRACE_OUTPUT_FIELD_NUMBER: builtins.int
    ANALYZE_TASK_OUTPUT_FIELD_NUMBER: builtins.int
    FUZZ_TASK_OUTPUT_FIELD_NUMBER: builtins.int
    MINIMIZE_TASK_OUTPUT_FIELD_NUMBER: builtins.int
    REGRESSION_TASK_OUTPUT_FIELD_NUMBER: builtins.int
    PROGRESSION_TASK_OUTPUT_FIELD_NUMBER: builtins.int
    SYMBOLIZE_TASK_OUTPUT_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    @property
    def testcase(self) -> global___UworkerEntityWrapper: ...
    @property
    def testcase_upload_metadata(self) -> global___UworkerEntityWrapper: ...
    @property
    def variant(self) -> global___UworkerEntityWrapper: ...
    error_type: global___ErrorType.ValueType
    @property
    def uworker_input(self) -> global___Input:
        """This is only to be used by code that needs to be called by utasks and
        nonutasks.
        """
    test_timeout: builtins.float
    crash_time: builtins.float
    crash_stacktrace_output: builtins.str
    @property
    def analyze_task_output(self) -> global___AnalyzeTaskOutput: ...
    @property
    def fuzz_task_output(self) -> global___FuzzTaskOutput: ...
    @property
    def minimize_task_output(self) -> global___MinimizeTaskOutput: ...
    @property
    def regression_task_output(self) -> global___RegressionTaskOutput: ...
    @property
    def progression_task_output(self) -> global___ProgressionTaskOutput: ...
    @property
    def symbolize_task_output(self) -> global___SymbolizeTaskOutput: ...
    error_message: builtins.str
    def __init__(
        self,
        *,
        testcase: global___UworkerEntityWrapper | None = ...,
        testcase_upload_metadata: global___UworkerEntityWrapper | None = ...,
        variant: global___UworkerEntityWrapper | None = ...,
        error_type: global___ErrorType.ValueType | None = ...,
        uworker_input: global___Input | None = ...,
        test_timeout: builtins.float | None = ...,
        crash_time: builtins.float | None = ...,
        crash_stacktrace_output: builtins.str | None = ...,
        analyze_task_output: global___AnalyzeTaskOutput | None = ...,
        fuzz_task_output: global___FuzzTaskOutput | None = ...,
        minimize_task_output: global___MinimizeTaskOutput | None = ...,
        regression_task_output: global___RegressionTaskOutput | None = ...,
        progression_task_output: global___ProgressionTaskOutput | None = ...,
        symbolize_task_output: global___SymbolizeTaskOutput | None = ...,
        error_message: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_analyze_task_output", b"_analyze_task_output", "_crash_stacktrace_output", b"_crash_stacktrace_output", "_crash_time", b"_crash_time", "_error_message", b"_error_message", "_error_type", b"_error_type", "_fuzz_task_output", b"_fuzz_task_output", "_minimize_task_output", b"_minimize_task_output", "_progression_task_output", b"_progression_task_output", "_regression_task_output", b"_regression_task_output", "_symbolize_task_output", b"_symbolize_task_output", "_test_timeout", b"_test_timeout", "_testcase", b"_testcase", "_testcase_upload_metadata", b"_testcase_upload_metadata", "_uworker_input", b"_uworker_input", "_variant", b"_variant", "analyze_task_output", b"analyze_task_output", "crash_stacktrace_output", b"crash_stacktrace_output", "crash_time", b"crash_time", "error_message", b"error_message", "error_type", b"error_type", "fuzz_task_output", b"fuzz_task_output", "minimize_task_output", b"minimize_task_output", "progression_task_output", b"progression_task_output", "regression_task_output", b"regression_task_output", "symbolize_task_output", b"symbolize_task_output", "test_timeout", b"test_timeout", "testcase", b"testcase", "testcase_upload_metadata", b"testcase_upload_metadata", "uworker_input", b"uworker_input", "variant", b"variant"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_analyze_task_output", b"_analyze_task_output", "_crash_stacktrace_output", b"_crash_stacktrace_output", "_crash_time", b"_crash_time", "_error_message", b"_error_message", "_error_type", b"_error_type", "_fuzz_task_output", b"_fuzz_task_output", "_minimize_task_output", b"_minimize_task_output", "_progression_task_output", b"_progression_task_output", "_regression_task_output", b"_regression_task_output", "_symbolize_task_output", b"_symbolize_task_output", "_test_timeout", b"_test_timeout", "_testcase", b"_testcase", "_testcase_upload_metadata", b"_testcase_upload_metadata", "_uworker_input", b"_uworker_input", "_variant", b"_variant", "analyze_task_output", b"analyze_task_output", "crash_stacktrace_output", b"crash_stacktrace_output", "crash_time", b"crash_time", "error_message", b"error_message", "error_type", b"error_type", "fuzz_task_output", b"fuzz_task_output", "minimize_task_output", b"minimize_task_output", "progression_task_output", b"progression_task_output", "regression_task_output", b"regression_task_output", "symbolize_task_output", b"symbolize_task_output", "test_timeout", b"test_timeout", "testcase", b"testcase", "testcase_upload_metadata", b"testcase_upload_metadata", "uworker_input", b"uworker_input", "variant", b"variant"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_analyze_task_output", b"_analyze_task_output"]) -> typing_extensions.Literal["analyze_task_output"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_crash_stacktrace_output", b"_crash_stacktrace_output"]) -> typing_extensions.Literal["crash_stacktrace_output"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_crash_time", b"_crash_time"]) -> typing_extensions.Literal["crash_time"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_error_message", b"_error_message"]) -> typing_extensions.Literal["error_message"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_error_type", b"_error_type"]) -> typing_extensions.Literal["error_type"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_fuzz_task_output", b"_fuzz_task_output"]) -> typing_extensions.Literal["fuzz_task_output"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_minimize_task_output", b"_minimize_task_output"]) -> typing_extensions.Literal["minimize_task_output"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_progression_task_output", b"_progression_task_output"]) -> typing_extensions.Literal["progression_task_output"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_regression_task_output", b"_regression_task_output"]) -> typing_extensions.Literal["regression_task_output"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_symbolize_task_output", b"_symbolize_task_output"]) -> typing_extensions.Literal["symbolize_task_output"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_test_timeout", b"_test_timeout"]) -> typing_extensions.Literal["test_timeout"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_testcase", b"_testcase"]) -> typing_extensions.Literal["testcase"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_testcase_upload_metadata", b"_testcase_upload_metadata"]) -> typing_extensions.Literal["testcase_upload_metadata"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_uworker_input", b"_uworker_input"]) -> typing_extensions.Literal["uworker_input"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_variant", b"_variant"]) -> typing_extensions.Literal["variant"] | None: ...

global___Output = Output
