from typing import Any, Callable, ContextManager, Dict, Optional, TypeVar

_T = TypeVar('_T')

class ContextOptions:
    def __init__(self, **kwargs: Any) -> None: ...

class TransactionOptions:
    NESTED: int
    MANDATORY: int
    ALLOWED: int
    INDEPENDENT: int
    def __init__(self, **kwargs: Any) -> None: ...

class AutoBatcher: ...

class Context:
    def __init__(self, client: Any, **kwargs: Any) -> None: ...
    def use(self) -> ContextManager['Context']: ...
    def __enter__(self) -> 'Context': ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    def clear_cache(self) -> None: ...
    def flush(self) -> None: ...
    def set_memcache_policy(self, policy: Any) -> None: ...
    def set_cache_policy(self, policy: Any) -> None: ...

class _State:
    context: Optional[Context]

_state: _State

def get_context(raise_context_error: bool = True) -> Optional[Context]: ...
def get_toplevel_context() -> Context: ...
def transactional(
    retries: int = 3,
    read_only: bool = False,
    propagation: Optional[int] = None,
    xg: bool = False,
) -> Callable[[Callable[..., _T]], Callable[..., _T]]: ...
def transactional_async(
    retries: int = 3,
    read_only: bool = False,
    propagation: Optional[int] = None,
    xg: bool = False,
) -> Callable[[Callable[..., _T]], Callable[..., _T]]: ...
def transactional_tasklet(
    retries: int = 3,
    read_only: bool = False,
    propagation: Optional[int] = None,
    xg: bool = False,
) -> Callable[[Callable[..., _T]], Callable[..., _T]]: ...
def non_transactional(
    allow_existing: bool = True,
) -> Callable[[Callable[..., _T]], Callable[..., _T]]: ...
