from typing import Any, Iterator, List, Optional, Sequence, Tuple, Union, overload

class Key:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def id(self) -> Any: ...
    def string_id(self) -> Optional[str]: ...
    def integer_id(self) -> Optional[int]: ...
    def kind(self) -> str: ...
    def parent(self) -> Optional['Key']: ...
    def root(self) -> 'Key': ...
    def pairs(self) -> Tuple[Tuple[str, Union[int, str]], ...]: ...
    def flat(self) -> Tuple[Union[str, int], ...]: ...
    def app(self) -> str: ...
    def namespace(self) -> Optional[str]: ...
    def urlsafe(self) -> bytes: ...
    def get(self, **kwargs: Any) -> Optional[Any]: ...
    def get_async(self, **kwargs: Any) -> Any: ...
    def delete(self, **kwargs: Any) -> None: ...
    def delete_async(self, **kwargs: Any) -> Any: ...
    @classmethod
    def from_old_key(cls, old_key: Any) -> 'Key': ...
    def to_old_key(self) -> Any: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
