from typing import Any, Generic, Iterable, Iterator, List, Optional, Sequence, Tuple, Type, TypeVar, Union

_M = TypeVar('_M')

class Node:
    def __and__(self, other: 'Node') -> 'ConjunctionNode': ...
    def __or__(self, other: 'Node') -> 'DisjunctionNode': ...
    def __invert__(self) -> 'Node': ...

class FalseNode(Node): ...
class ParameterNode(Node): ...

class FilterNode(Node):
    name: str
    opsymbol: str
    value: Any
    def __init__(self, name: str, opsymbol: str, value: Any) -> None: ...

class ConjunctionNode(Node):
    nodes: List[Node]
    def __init__(self, *nodes: Node) -> None: ...

class DisjunctionNode(Node):
    nodes: List[Node]
    def __init__(self, *nodes: Node) -> None: ...

def AND(*nodes: Node) -> ConjunctionNode: ...
def OR(*nodes: Node) -> DisjunctionNode: ...

class PropertyOrder:
    name: str
    reverse: bool
    def __init__(self, name: str, reverse: bool = False) -> None: ...
    def __neg__(self) -> 'PropertyOrder': ...

class Cursor:
    def __init__(self, urlsafe: Optional[Union[bytes, str]] = None) -> None: ...
    def urlsafe(self) -> bytes: ...

class QueryIterator(Iterator[_M], Generic[_M]):
    def cursor_after(self) -> Cursor: ...
    def cursor_before(self) -> Cursor: ...
    def __iter__(self) -> 'QueryIterator[_M]': ...
    def __next__(self) -> _M: ...

class Query(Generic[_M]):
    kind: Optional[str]
    ancestor: Optional[Any]
    filters: Optional[Node]
    orders: Optional[List[PropertyOrder]]
    namespace: Optional[str]
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def filter(self, *filters: Node) -> 'Query[_M]': ...
    def order(self, *orders: Union[PropertyOrder, Any]) -> 'Query[_M]': ...
    def fetch(self, limit: Optional[int] = None, **kwargs: Any) -> List[_M]: ...
    def fetch_async(self, limit: Optional[int] = None, **kwargs: Any) -> Any: ...
    def fetch_page(self, page_size: int, **kwargs: Any) -> Tuple[List[_M], Optional[Cursor], bool]: ...
    def fetch_page_async(self, page_size: int, **kwargs: Any) -> Any: ...
    def get(self, **kwargs: Any) -> Optional[_M]: ...
    def get_async(self, **kwargs: Any) -> Any: ...
    def count(self, limit: Optional[int] = None, **kwargs: Any) -> int: ...
    def count_async(self, limit: Optional[int] = None, **kwargs: Any) -> Any: ...
    def iter(self, **kwargs: Any) -> QueryIterator[_M]: ...
    def __iter__(self) -> QueryIterator[_M]: ...

def gql(query_string: str, *args: Any, **kwds: Any) -> Query[Any]: ...
