from typing import Any, Callable, Generator, Generic, Optional, TypeVar, Union

_T = TypeVar('_T')

class Future(Generic[_T]):
    def __init__(self, info: Optional[str] = None) -> None: ...
    def done(self) -> bool: ...
    def running(self) -> bool: ...
    def wait(self) -> None: ...
    def get_result(self) -> _T: ...
    def check_success(self) -> None: ...
    def set_result(self, result: _T) -> None: ...
    def set_exception(self, exception: Any) -> None: ...
    def add_done_callback(self, callback: Callable[['Future[_T]'], Any]) -> None: ...
    def add_immediate_callback(self, callback: Callable[['Future[_T]'], Any]) -> None: ...
    @classmethod
    def wait_any(cls, futures: Any) -> 'Future[Any]': ...
    @classmethod
    def wait_all(cls, futures: Any) -> None: ...

def tasklet(
    func: Callable[..., Union[Generator[Any, Any, _T], _T]]
) -> Callable[..., Future[_T]]: ...

def Return(result: _T) -> None: ...
def sleep(seconds: float) -> Future[None]: ...
def add_flow_variable(name: str, initial_value: Any = None) -> Any: ...
