# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: batch/v1
kind: CronJob
metadata:
  name: schedule-upload-reports-tasks
  namespace: default
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - env:
            - name: RUN_CMD
              value: python3.11 $ROOT_DIR/src/python/bot/startup/run_cron.py schedule_upload_reports_tasks
            - name: IS_K8S_ENV
              value: "true"
            - name: DISABLE_MOUNTS
              value: "true"
            image: gcr.io/clusterfuzz-images/base:vguidi_py311_testing_v1
            imagePullPolicy: Always
            name: schedule-upload-reports-tasks
          restartPolicy: OnFailure
  schedule: 0 */3 * * *
  successfulJobsHistoryLimit: 3
