#!/bin/bash -ex
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################

TEST_NAME=$1
shift

echo "Running untrusted integration tests for $TEST_NAME..."
UNTRUSTED_RUNNER_TESTS=1 python butler.py py_unittest -t core -p \*"$TEST_NAME"\* "$@"
