#!/bin/bash -ex
SCRIPT_DIR=$(dirname $(readlink -f "$0"))

INTEGRATION=1 $SCRIPT_DIR/run_tests
$SCRIPT_DIR/run_ndb_patcher_tests
$SCRIPT_DIR/run_reproduce_tool_tests
$SCRIPT_DIR/run_js_tests
$SCRIPT_DIR/run_untrusted_test untrusted_runner_integration
$SCRIPT_DIR/run_untrusted_test corpus_pruning
$SCRIPT_DIR/run_afl_tests

echo 'Running end-to-end integration tests...'
python butler.py integration_tests
