load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "io_bazel_rules_go",
    urls = [
        "https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/rules_go/releases/download/0.18.6/rules_go-0.18.6.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/0.18.6/rules_go-0.18.6.tar.gz",
    ],
    sha256 = "f04d2373bcaf8aa09bccb08a98a57e721306c8f6043a2a0ee610fd6853dcde3d",
)
http_archive(
    name = "bazel_gazelle",
    urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/0.17.0/bazel-gazelle-0.17.0.tar.gz"],
    sha256 = "3c681998538231a2d24d0c07ed5a7658cb72bfb5fd4bf9911157c0e9ac6a2687",
)
http_archive(
    name = "net_zlib",
    build_file = "@com_google_protobuf//:third_party/zlib.BUILD",
    strip_prefix = "zlib-1.2.11",
    urls = ["https://mirror.bazel.build/zlib.net/zlib-1.2.11.tar.gz"],
    sha256 = "c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1",
)
bind(
    name = "zlib",
    actual = "@net_zlib//:zlib",
)
load("@io_bazel_rules_go//go:deps.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")
gazelle_dependencies()

# Google Cloud client libraries.
go_repository(
    name = "com_google_cloud_go",
    commit = "0ebda48a7f143b1cce9eb37a8c1106ac762a3430",  # v0.34.0
    importpath = "cloud.google.com/go",
)

go_repository(
    name = "org_golang_google_api",
    commit = "146117f78c63efe78e04021cc321e59fb3c13e50",  # master as of 2018-12-19
    importpath = "google.golang.org/api",
)

go_repository(
    name = "com_github_googleapis_gax_go",
    commit = "b001040cd31805261cbd978842099e326dfa857b",  # v2.0.2
    importpath = "github.com/googleapis/gax-go",
)

go_repository(
    name = "org_golang_x_oauth2",
    commit = "d668ce993890a79bda886613ee587a69dd5da7a6",  # master as of 2018-12-03
    importpath = "golang.org/x/oauth2",
)

go_repository(
    name = "org_golang_x_sync",
    commit = "42b317875d0fa942474b76e1b46a6060d720ae6e",  # master as of 2018-11-07
    importpath = "golang.org/x/sync",
)

go_repository(
    name = "io_opencensus_go",
    commit = "b7bf3cdb64150a8c8c53b769fdeb2ba581bd4d4b",  # 0.18.0
    importpath = "go.opencensus.io",
)

go_repository(
    name = "io_opencensus_go_contrib_exporter_stackdriver",
    commit = "2b7f4fc93daf5ec3048fa4fc1c15573466711a17",  # 0.8.0
    importpath = "contrib.go.opencensus.io/exporter/stackdriver",
)

go_repository(
    name = "com_github_pkg_errors",
    commit = "645ef00459ed84a119197bfb8d8205042c6df63d",  # 0.8.0
    importpath = "github.com/pkg/errors",
)

go_repository(
    name = "com_github_shirou_gopsutil",
    commit = "0f70a4a06f7a1039305ec9b3ba9c2800f8929fba",  # v2.18.11
    importpath = "github.com/shirou/gopsutil",
)

go_repository(
    name = "in_gopkg_yaml_v2",
    commit = "51d6538a90f86fe93ac480b35f37b2be17fef232",  # v2.2.2
    importpath = "gopkg.in/yaml.v2",
)

go_repository(
    name = "org_golang_x_sys",
    commit = "41f3e6584952bb034a481797859f6ab34b6803bd",  # master as of 2019-02-04
    importpath = "golang.org/x/sys",
)
